### ISSUE TITLE
请问渲染失败如何解决？

### ISSUE THREAD

**Issue by Flyingpen** [tangly1024/NotionNext#1159]
```
Error occurred prerendering page "/tag/行动方案". Read more: https://nextjs.org/docs/messages/prerender-error
--
23:11:32.798 | Error: Error serializing `.siteInfo.icon` returned from `getStaticProps` in "/tag/[tag]".
23:11:32.798 | Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
23:11:32.798 | at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
23:11:32.798 | at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
23:11:32.798 | at Array.every (<anonymous>)
23:11:32.798 | at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
23:11:32.798 | at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
23:11:32.798 | at Array.every (<anonymous>)
23:11:32.798 | at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
23:11:32.798 | at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
23:11:32.798 | at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
23:11:32.798 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
23:11:32.798 | info  - Generating static pages (268/268)
```

我是fork了之后，用vercel部署的，就在今天vercel报错，然后出现渲染失败。chatGPT的说法是：

> 该错误是在 Next.js SSR（服务器端渲染）过程中发生的，并包含了以下错误信息：
> 在渲染页面“/article%2Fe1113ad5-616d-4e23-a664-c04417108461.html”时发生了错误。该页面的数据是在getStaticProps 方法中获取的。错误信息显示，由于JSON序列化返回了undefined，而 undefined 无法被 JSON 序列化。因此，错误的原因是在应用程序代码中从 getStaticProps 中返回了 undefined 值。
> 为了解决这个问题，我们需要检查代码中是否存在没有返回值或返回undefined的getStaticProps方法。需要注意的是，Next.js在执行getStaticProps时要求必须返回一个对象。如果在方法中省略了返回语句，或者自行返回了undefined， 会导致此类错误的发生。
> 因此，我们应该在getStaticProps 中确保返回正确的对象，同时保证该对象的所有属性均可以被 JSON 序列化。
> 

请问如何解决?

**Comment by ottocsb** [comment]
[@1144](https://github.com/tangly1024/NotionNext/issues/1144)
相同的问题，我补充了下日志最后的错误信息

**Comment by Flyingpen** [comment]
猜测大概是3.15.1的更新问题，我是先拉取了作者大大的最新更新，后出现的渲染失败情况。
等待作者大大解决吧。应该会很快的。

**Comment by tangly1024** [comment]
已提交补丁修复编译打包问题 https://github.com/tangly1024/NotionNext/commit/20917b47a49e29f2c53914d06c81bcfa44f34183
