### ISSUE TITLE
[部署错误]  Incorrect locale information provided ,设置二级菜单后Vercel报错

### ISSUE THREAD

**Issue by jarrett-au** [tangly1024/NotionNext#1173]
**问题**
之前使用 `Page` 时使用是正常的，现在想改用二级菜单，在 Vercel 环境变量中已经设置了 `NEXT_PUBLIC_CUSTOM_MENU` 为 `true`，然后参考 Notion 模板设置了 `Menu` 和 `SubMenu`，再重新部署就失败了。以下为部署日志：
```
[09:35:07.125] Running build in Cleveland, USA (East) – cle1
[09:35:07.177] Cloning github.com/jarrett-au/NotionNext (Branch: main, Commit: 133fdd7)
[09:35:07.182] Skipping build cache, deployment was triggered without cache.
[09:35:07.644] Cloning completed: 466.629ms
[09:35:07.779] Running "vercel build"
[09:35:08.258] Vercel CLI 30.2.1
[09:35:08.507] Installing dependencies...
[09:35:08.758] yarn install v1.22.17
[09:35:08.790] info No lockfile found.
[09:35:08.796] [1/4] Resolving packages...
[09:35:18.348] warning react-notion-x > react-use > nano-css > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[09:35:25.325] [2/4] Fetching packages...
[09:35:37.776] [3/4] Linking dependencies...
[09:35:37.778] warning " > qrcode.react@1.0.1" has incorrect peer dependency "react@^15.5.3 || ^16.0.0 || ^17.0.0".
[09:35:37.778] warning " > react-cusdis@2.1.3" has incorrect peer dependency "react@^17.0.0".
[09:35:37.778] warning " > react-cusdis@2.1.3" has incorrect peer dependency "react-dom@^17.0.0".
[09:35:37.778] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[09:35:37.778] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[09:35:37.779] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[09:35:37.779] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[09:35:37.779] warning "react-notion-x > react-image@4.1.0" has unmet peer dependency "@babel/runtime@>=7".
[09:35:37.779] warning "react-notion-x > react-lazy-images > react-intersection-observer@6.4.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
[09:35:37.779] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[09:35:37.780] warning " > use-ackee@3.0.1" has incorrect peer dependency "react@^17.0.0".
[09:35:37.780] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[09:35:51.198] [4/4] Building fresh packages...
[09:35:51.359] success Saved lockfile.
[09:35:51.364] Done in 42.61s.
[09:35:51.428] Detected Next.js version: 13.3.1
[09:35:51.430] Running "yarn run build"
[09:35:51.595] yarn run v1.22.17
[09:35:51.630] $ next build
[09:35:51.886] info  - Loaded env from /vercel/path0/.env.local
[09:35:52.161] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[09:35:52.161] This information is used to shape Next.js' roadmap and prioritize features.
[09:35:52.161] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[09:35:52.161] https://nextjs.org/telemetry
[09:35:52.161] 
[09:35:52.489] info  - Linting and checking validity of types...
[09:35:55.103] info  - Creating an optimized production build...
[09:36:12.330] info  - Compiled successfully
[09:36:12.337] info  - Collecting page data...
[09:36:13.139] [请求API] from:category-paths id:14daf88f2ddc47918b4e210d72246927 
[09:36:13.149] [请求API] from:category-paths id:14daf88f2ddc47918b4e210d72246927 
[09:36:13.255] [请求API] from:slug-paths id:14daf88f2ddc47918b4e210d72246927 
[09:36:13.255] [请求API] from:page-paths id:14daf88f2ddc47918b4e210d72246927 
[09:36:13.599] [响应成功]: from:category-paths
[09:36:13.599] [API耗时] 451ms
[09:36:13.605] RangeError: Incorrect locale information provided
[09:36:13.605]     at Date.toLocaleDateString (<anonymous>)
[09:36:13.605]     at formatDate (/vercel/path0/.next/server/chunks/3151.js:235:19)
[09:36:13.605]     at getPageProperties (/vercel/path0/.next/server/chunks/3151.js:878:94)
[09:36:13.605]     at getDataBaseInfoByNotionAPI (/vercel/path0/.next/server/chunks/3151.js:693:105)
[09:36:13.605]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:36:13.605]     at async getNotionPageData (/vercel/path0/.next/server/chunks/3151.js:503:27)
[09:36:13.605]     at async getGlobalNotionData (/vercel/path0/.next/server/chunks/3151.js:462:88)
[09:36:13.605]     at async getStaticPaths (/vercel/path0/.next/server/pages/category/[category]/page/[page].js:106:45)
[09:36:13.605]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:673:33)
[09:36:13.606]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1099:113
[09:36:13.607] 
[09:36:13.607] > Build error occurred
[09:36:13.609] Error: Failed to collect page data for /category/[category]/page/[page]
[09:36:13.609]     at /vercel/path0/node_modules/next/dist/build/utils.js:1130:15
[09:36:13.609]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[09:36:13.609]   type: 'Error'
[09:36:13.609] }
[09:36:13.664] error Command failed with exit code 1.
[09:36:13.664] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[09:36:13.686] Error: Command "yarn run build" exited with 1
[09:36:14.089] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**相应配置**
`notion_page_id`: 14daf88f2ddc47918b4e210d72246927
`website`: blog.coding-park.top

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/54349564/0382a27e-75f3-4bb1-b993-7d146ef72217)

**环境**

- 操作系统: Windows
- 浏览器 Chrome
- 版本 104.0.5112.102（正式版本） （64 位）

**Comment by tangly1024** [comment]
检查一下 您verlcel后台的环境变量

`NEXT_PUBLIC_LANG` 博客语言的环境变量 支持 'zh-CN','en-US'等等如果配置有误会导致编译失败。

**Comment by jarrett-au** [comment]
感谢，确实是语言设置有误！问题已解决~
