### ISSUE TITLE
[部署失败] cloudflare pages部署失败，看起来是sitemap的部分报的错

### ISSUE THREAD

**Issue by lgeger** [tangly1024/NotionNext#1265]
**描述遇到的问题**
按照教程，copy了大佬的deploy/cloudflare-support分支，然后什么都没有改动，去cloudflare部署，我的配置如下：
![image](https://github.com/tangly1024/NotionNext/assets/87757171/40a4af45-77b1-4597-ae12-4b7b9791a090)
但是部署不成功，报错。

**相应配置**
构建命令： npm run export
构建输出目录： /out

NEXT_PUBLIC_THEME | medium
NODE_VERSION | 16
NOTION_PAGE_ID | 26e18c8ce56b4adb832a2146d5ab5afe
VERCEL_ENV | production

**截图**

![image](https://github.com/tangly1024/NotionNext/assets/87757171/7fa170b1-2821-4a24-855b-806d7f94337f)

报错日志：
<html>
<body>

15:02:17.865 | [API耗时] 75ms
-- | --
15:02:17.870 | [请求API] from:rss-content id:1cfe4246-9478-4bb3-b24d-fa04acccb89c
15:02:17.923 | /opt/buildhome/repo/.next/server/pages/index.js:241
15:02:17.924 | async function generateSitemapXml({ allPages }) {
15:02:17.924 | ^
15:02:17.924 |  
15:02:17.924 | TypeError: Cannot destructure property 'allPages' of 'undefined' as it is undefined.
15:02:17.924 | at generateSitemapXml (/opt/buildhome/repo/.next/server/pages/index.js:241:37)
15:02:17.925 | at getStaticProps (/opt/buildhome/repo/.next/server/pages/index.js:372:82)
15:02:17.925 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
15:02:18.009 | [响应成功]: from:slug
15:02:18.009 | [API耗时] 104ms
15:02:18.012 | [请求API] from:slug-props-example-8 id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:18.032 | [响应成功]: from:slug
15:02:18.033 | [API耗时] 167ms
15:02:18.060 | [请求API] from:slug-props-example-9 id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:18.272 | [响应成功]: from:slug-props-example-8
15:02:18.272 | [API耗时] 259ms
15:02:18.293 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:18.327 | [响应成功]: from:slug-props-example-9
15:02:18.328 | [API耗时] 268ms
15:02:18.341 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:18.368 | [响应成功]: from:data-notice
15:02:18.369 | [API耗时] 75ms
15:02:18.372 | [请求API] from:slug id:c1e9d153-cdd8-4ae0-badd-b392d1074f1f
15:02:18.421 | [响应成功]: from:data-notice
15:02:18.422 | [API耗时] 80ms
15:02:18.424 | [请求API] from:slug id:59acc450-0742-42cb-ac96-5f4f674b0ef6
15:02:18.471 | [响应成功]: from:slug
15:02:18.472 | [API耗时] 101ms
15:02:18.507 | [请求API] from:slug-props-example-10 id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:18.557 | [响应成功]: from:slug
15:02:18.558 | [API耗时] 133ms
15:02:18.597 | [请求API] from:slug-props-5dddcd4a-536c-43ee-a214-d62fc9af0aba id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:18.767 | [响应成功]: from:slug-props-example-10
15:02:18.768 | [API耗时] 262ms
15:02:18.780 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:18.854 | [响应成功]: from:data-notice
15:02:18.854 | [API耗时] 73ms
15:02:18.858 | [请求API] from:slug id:c630ea59-6694-48fa-97d4-9c3bde0e8add
15:02:18.883 | [响应成功]: from:slug-props-5dddcd4a-536c-43ee-a214-d62fc9af0aba
15:02:18.884 | [API耗时] 288ms
15:02:18.897 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:18.971 | [响应成功]: from:slug
15:02:18.971 | [API耗时] 111ms
15:02:18.995 | [响应成功]: from:data-notice
15:02:18.996 | [API耗时] 99ms
15:02:19.000 | [请求API] from:slug-props-invisible id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:19.000 | [请求API] from:slug id:5dddcd4a-536c-43ee-a214-d62fc9af0aba
15:02:19.039 | [请求API] from:index id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:19.142 | [响应成功]: from:slug
15:02:19.142 | [API耗时] 142ms
15:02:19.169 | [请求API] from:slug-props-message id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:19.267 | [响应成功]: from:slug-props-invisible
15:02:19.267 | [API耗时] 270ms
15:02:19.281 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:19.353 | [响应成功]: from:data-notice
15:02:19.353 | [API耗时] 71ms
15:02:19.355 | [请求API] from:slug id:4dc79344-4324-4cec-a982-720288bf7181
15:02:19.389 | [响应成功]: from:index
15:02:19.389 | [API耗时] 351ms
15:02:19.422 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:19.444 | [响应成功]: from:slug
15:02:19.445 | [API耗时] 89ms
15:02:19.471 | [响应成功]: from:slug-props-message
15:02:19.472 | [API耗时] 302ms
15:02:19.475 | [请求API] from:slug-props-links id:26e18c8ce56b4adb832a2146d5ab5afe
15:02:19.492 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:19.497 | [响应成功]: from:data-notice
15:02:19.497 | [API耗时] 75ms
15:02:19.502 | [请求API] from:rss-content id:1cfe4246-9478-4bb3-b24d-fa04acccb89c
15:02:19.554 | /opt/buildhome/repo/.next/server/pages/index.js:241
15:02:19.555 | async function generateSitemapXml({ allPages }) {
15:02:19.555 | ^
15:02:19.555 |  
15:02:19.555 | TypeError: Cannot destructure property 'allPages' of 'undefined' as it is undefined.
15:02:19.555 | at generateSitemapXml (/opt/buildhome/repo/.next/server/pages/index.js:241:37)
15:02:19.556 | at getStaticProps (/opt/buildhome/repo/.next/server/pages/index.js:372:82)
15:02:19.556 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
15:02:19.626 |  
15:02:19.626 | > Build error occurred
15:02:19.629 | Error: Call retries were exceeded
15:02:19.630 | at ChildProcessWorker.initialize (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
15:02:19.630 | at ChildProcessWorker._onExit (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
15:02:19.630 | at ChildProcess.emit (node:events:513:28)
15:02:19.630 | at ChildProcess.emit (node:domain:489:12)
15:02:19.630 | at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
15:02:19.631 | type: 'WorkerError'
15:02:19.631 | }
15:02:19.736 | Failed: Error while executing user command. Exited with error code: 1
15:02:19.750 | Failed: build command exited with code: 1
15:02:20.908 | Failed: error occurred while running build command

</body>
</html>

**Comment by lgeger** [comment]
重新贴一下报错日志：
`<html>
<body>


15:02:19.475 | [请求API] from:slug-props-links id:26e18c8ce56b4adb832a2146d5ab5afe
-- | --
15:02:19.492 | [请求API] from:data-notice id:b1da18c8-3b99-497e-b179-d59927527bcd
15:02:19.497 | [响应成功]: from:data-notice
15:02:19.497 | [API耗时] 75ms
15:02:19.502 | [请求API] from:rss-content id:1cfe4246-9478-4bb3-b24d-fa04acccb89c
15:02:19.554 | /opt/buildhome/repo/.next/server/pages/index.js:241
15:02:19.555 | async function generateSitemapXml({ allPages }) {
15:02:19.555 | ^
15:02:19.555 |  
15:02:19.555 | TypeError: Cannot destructure property 'allPages' of 'undefined' as it is undefined.
15:02:19.555 | at generateSitemapXml (/opt/buildhome/repo/.next/server/pages/index.js:241:37)
15:02:19.556 | at getStaticProps (/opt/buildhome/repo/.next/server/pages/index.js:372:82)
15:02:19.556 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
15:02:19.626 |  
15:02:19.626 | > Build error occurred
15:02:19.629 | Error: Call retries were exceeded
15:02:19.630 | at ChildProcessWorker.initialize (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
15:02:19.630 | at ChildProcessWorker._onExit (/opt/buildhome/repo/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
15:02:19.630 | at ChildProcess.emit (node:events:513:28)
15:02:19.630 | at ChildProcess.emit (node:domain:489:12)
15:02:19.630 | at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
15:02:19.631 | type: 'WorkerError'
15:02:19.631 | }
15:02:19.736 | Failed: Error while executing user command. Exited with error code: 1
15:02:19.750 | Failed: build command exited with code: 1
15:02:20.908 | Failed: error occurred while running build command


</body>
</html>`

**Comment by lgeger** [comment]
使用main分支部署没问题了
