### ISSUE TITLE
[部署错误] vercel 部署失败, TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by wanghaoxi3000** [tangly1024/NotionNext#1267]
**描述遇到的问题**
vercel 部署失败

之前一直是可以正常部署的，最近迁移了旧博客的文章，改了 next 主题的 footer，再部署就会报错了

**相应配置**
Fork 项目：https://github.com/wanghaoxi3000/NotionNext
notion_page_id：ae3c8c9fd2e7490cb2980f96e33fe57e
网站地址：https://darkreunion.tech/

**截图**
```


/vercel/path0/.next/server/chunks/635.js:6583
--
17:45:24.762 | const defaultCollectionViewId = viewIds[0];
17:45:24.762 | ^
17:45:24.762 |  
17:45:24.762 | TypeError: Cannot read properties of undefined (reading '0')
17:45:24.762 | at CollectionViewBlock (/vercel/path0/.next/server/chunks/635.js:6583:42)
17:45:24.762 | at Fb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
17:45:24.762 | at Ib (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
17:45:24.762 | at W (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
17:45:24.762 | at Ib (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:71:304)
17:45:24.762 | at W (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
17:45:24.762 | at Ib (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
17:45:24.762 | at W (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
17:45:24.763 | at Ib (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
17:45:24.763 | at W (/vercel/path0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
17:45:24.763 |  
17:45:24.763 | Node.js v18.16.1
17:45:24.767 | [响应成功]: from:slug-props-article/life-stream-2305-W1
17:45:24.767 | [API耗时] 141ms
17:45:24.806 | Static worker unexpectedly exited with code: 1 and signal: null


17:45:38.477 | TypeError: Cannot read properties of undefined (reading '0')
17:45:38.477 | at CollectionViewBlock (/vercel/path0/.next/server/chunks/635.js:6583:42)
17:45:38.477 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
17:45:38.477 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
17:45:38.477 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.477 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
17:45:38.477 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.477 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
17:45:38.477 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.477 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
17:45:38.477 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.478 |  
17:45:38.478 | Error occurred prerendering page "/article%2Fgolang-gc". Read more: https://nextjs.org/docs/messages/prerender-error
17:45:38.478 | TypeError: Cannot read properties of undefined (reading '0')
17:45:38.478 | at CollectionViewBlock (/vercel/path0/.next/server/chunks/635.js:6583:42)
17:45:38.478 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
17:45:38.478 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
17:45:38.478 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.478 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
17:45:38.478 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.478 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
17:45:38.478 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
17:45:38.478 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
17:45:38.478 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)


17:47:35.710 | Static worker unexpectedly exited with code: null and signal: SIGTERM
17:47:35.712 | Static worker unexpectedly exited with code: null and signal: SIGTERM
17:47:35.713 | Static worker unexpectedly exited with code: null and signal: SIGTERM
17:47:35.714 | warn  - Restarted static page generation for /article%2Fgolang-scheduler because it took more than 60 seconds
17:47:35.714 | warn  - See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
17:47:35.714 | warn  - Restarted static page generation for /article%2Fuse-gin-and-websocket-to-play-rtsp-video because it took more than 60 seconds
17:47:35.714 | warn  - Restarted static page generation for /article%2Fdeploy-kubernetes-on-ubuntu18 because it took more than 60 seconds
17:47:35.714 | warn  - Restarted static page generation for /article%2Fseckill-backend-system-base-on-go-micro because it took more than 60 seconds
17:47:35.714 | warn  - Restarted static page generation for /article%2Ffirst-exploration-of-mirco-service because it took more than 60 seconds
17:47:35.714 | warn  - Restarted static page generation for /article%2Fuse-ci-system-to-free-time because it took more than 60 seconds
17:47:35.714 | warn  - Restarted static page generation for /article%2Fgo-base-knowledge because it took more than 60 seconds
17:47:35.715 | warn  - Restarted static page generation for /article%2Fversatility-uwsgi-config because it took more than 60 seconds
17:47:35.715 | warn  - Restarted static page generation for /article%2Fmanage-hexo-theme-with-git-submodules because it took more than 60 seconds
17:47:35.715 | warn  - Restarted static page generation for /article%2Falgorithm-with-leetcode because it took more than 60 seconds
17:47:35.715 | warn  - Restarted static page generation for /article%2Fpython-build-in-function because it took more than 60 seconds
17:47:35.716 | warn  - Restarted static page generation for /article%2Fsometimes-useful-mysql-skill because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fsometimes-useful-git-skill because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fpandas-basic-usage because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fnumpy-basic-usage because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fmysql-config-adjust because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Frunning-crontab-in-docker because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fdjango-hides-the-primary-key-id-in-the-database-with-hash because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fvirtualenvwrapper-of-the-python-module because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Flinux-common-commands because it took more than 60 seconds
17:47:35.717 | warn  - Restarted static page generation for /article%2Fshell-edit-the-crontab-task because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fcpp11-new-knowledge-point because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fnotes-on-the-design-pattern-of-big-talk because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fes6-scope-and-deconstruction-assignment because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fthe-class-object-of-the-thinking-mapping-java because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fjava-io-learning-point-guide because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fjavascript-function because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fthe-basic-concept-of-javascript-closure because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fjavascript-type-comparison because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fcollections-of-the-python-module because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fpython-advanced-decorator because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fpython-advanced-iterator-and-generator because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fbrief-explanation-of-event-driven-(python-implementation) because it took more than 60 seconds
17:47:35.718 | warn  - Restarted static page generation for /article%2Fthe-configuration-program-becomes-a-linux-service because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fdjango-modelform-modifies-the-default-control-properties because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fdesign-pattern-of-django because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fsummary-of-shell-writing because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fmysql-will-surely-know-notes because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fandroid-activity-lifecycle because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fpython-small-knowledge-point because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fpython-tarfile-module-unzip-invalid-mode-('wb')-or-filename because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fmakefile-common-knowledge-points because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fpy2exe-conversion-parameters because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Flinux-driven-development-basic-knowledge because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /article%2Fvi-skills because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /message because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /links because it took more than 60 seconds
17:47:35.719 | warn  - Restarted static page generation for /%23 because it took more than 60 seconds
Expand 7 Lines
17:48:36.320 | Static worker unexpectedly exited with code: null and signal: SIGTERM
17:48:36.321 | warn  - Restarted static page generation for /article%2Fgolang-scheduler because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fuse-gin-and-websocket-to-play-rtsp-video because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fdeploy-kubernetes-on-ubuntu18 because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fseckill-backend-system-base-on-go-micro because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Ffirst-exploration-of-mirco-service because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fuse-ci-system-to-free-time because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fgo-base-knowledge because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fversatility-uwsgi-config because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fmanage-hexo-theme-with-git-submodules because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Falgorithm-with-leetcode because it took more than 60 seconds
17:48:36.321 | warn  - Restarted static page generation for /article%2Fpython-build-in-function because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fsometimes-useful-mysql-skill because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fsometimes-useful-git-skill because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fpandas-basic-usage because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fnumpy-basic-usage because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fmysql-config-adjust because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Frunning-crontab-in-docker because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fdjango-hides-the-primary-key-id-in-the-database-with-hash because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fvirtualenvwrapper-of-the-python-module because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Flinux-common-commands because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fshell-edit-the-crontab-task because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fcpp11-new-knowledge-point because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fnotes-on-the-design-pattern-of-big-talk because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fes6-scope-and-deconstruction-assignment because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fthe-class-object-of-the-thinking-mapping-java because it took more than 60 seconds
17:48:36.322 | warn  - Restarted static page generation for /article%2Fjava-io-learning-point-guide because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fjavascript-function because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fthe-basic-concept-of-javascript-closure because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fjavascript-type-comparison because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fcollections-of-the-python-module because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fpython-advanced-decorator because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fpython-advanced-iterator-and-generator because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fbrief-explanation-of-event-driven-(python-implementation) because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fthe-configuration-program-becomes-a-linux-service because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fdjango-modelform-modifies-the-default-control-properties because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fdesign-pattern-of-django because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fsummary-of-shell-writing because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fmysql-will-surely-know-notes because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fandroid-activity-lifecycle because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fpython-small-knowledge-point because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fpython-tarfile-module-unzip-invalid-mode-('wb')-or-filename because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fmakefile-common-knowledge-points because it took more than 60 seconds
17:48:36.323 | warn  - Restarted static page generation for /article%2Fpy2exe-conversion-parameters because it took more than 60 seconds
17:48:36.324 | warn  - Restarted static page generation for /article%2Flinux-driven-development-basic-knowledge because it took more than 60 seconds
17:48:36.324 | warn  - Restarted static page generation for /article%2Fvi-skills because it took more than 60 seconds
17:48:36.324 | warn  - Restarted static page generation for /message because it took more than 60 seconds
17:48:36.324 | warn  - Restarted static page generation for /links because it took more than 60 seconds
17:48:36.324 | warn  - Restarted static page generation for /%23 because it took more than 60 seconds
17:48:36.908 | [请求API] from:slug-props-article/golang-scheduler id:ae3c8c9fd2e7490cb2980f96e33fe57e
17:48:37.693 | [响应成功]: from:slug-props-article/golang-scheduler
17:48:37.693 | [API耗时] 786ms
17:48:37.738 | [请求API] from:data-notice id:129c8c93-bc35-4223-99da-1b04a34407b3
17:48:37.853 | [响应成功]: from:data-notice
17:48:37.853 | [API耗时] 115ms
17:48:37.864 | [请求API] from:slug-props-article/golang-scheduler id:0498bc63-4538-4d18-94f2-6edf9b92f43f
17:49:36.931 | Static worker unexpectedly exited with code: null and signal: SIGTERM
17:49:36.934 |  
17:49:36.935 | > Build error occurred
17:49:36.936 | Error: Static page generation for /article%2Fgolang-scheduler is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
17:49:36.936 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:647:35)
17:49:36.936 | at Worker.exportPage (/vercel/path0/node_modules/next/dist/lib/worker.js:88:40)
17:49:36.937 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17:49:36.937 | at async /vercel/path0/node_modules/next/dist/export/index.js:502:32
17:49:36.937 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:97:20)
17:49:36.937 | at async Promise.all (index 61)
17:49:36.937 | at async /vercel/path0/node_modules/next/dist/export/index.js:497:9
17:49:36.937 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:97:20)
17:49:36.937 | at async /vercel/path0/node_modules/next/dist/build/index.js:1440:21
17:49:36.937 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:97:20)
17:49:36.974 | error Command failed with exit code 1.
17:49:36.974 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:49:36.996 | Error: Command "yarn run build" exited with 1


```

**环境**
- 版本 v3.16.4

**Comment by tangly1024** [comment]
最近迁移了旧博客的文章

这里做了什么操作，看错误日志是，获取notion-api数据异常

**Comment by wanghaoxi3000** [comment]
@tangly1024 原来旧博客是 markdown 写的，就是把这些内容粘贴到了 notion 中，这个过程持续了几天，每天移过来一部分，4天前部署了一次是可以的。
另外删除了 type 为 menu 类型的菜单，暂时不会用到二级菜单功能，调整了数据表列的顺序不知道有没有影响，有尝试改回和模板一致还是无法部署。

**Comment by wanghaoxi3000** [comment]
@tangly1024 我在本地使用 yarn build 来构建测试了下，发现似乎是  https://www.notion.so/Golang-GC-e7a5493ca981423caef4931f010cbe1a 这篇文章导致了 `TypeError: Cannot read properties of undefined (reading '0')` 的问题，
把这篇文章改为 Draft 状态，即可正常构建了。

在构建完成后，重新设置为 Published 状态，文章标题和摘要可以在目录中显示，但是一点击进去就会出错变为空白页，vercel 的日志中可以查看到同样出现了 `TypeError: Cannot read properties of undefined (reading '0')` 的错误。

这篇文章我反复检查了几次，该有的属性都有，看起来和其他正常的文章没有什么不同... 不清楚出现此问题的原因了。

另外发现 404 页面显示 `页面无法加载，即将返回首页`，但实际并不会自动跳转到首页，比如我搭建的这个:  https://darkreunion.tech/404

**Comment by wanghaoxi3000** [comment]
升级到4.0.8 版本，404 页面可以正常跳转了，出错的页面手动重新复制了下，也可以正常构建了
