### ISSUE TITLE
【部署错误】主题默认为 nobelium 时部署错误

### ISSUE THREAD

**Issue by hjwucc** [tangly1024/NotionNext#1297]
**描述遇到的问题**
日志如下：
```js
14:53:32.890 | at BlogListScroll (/vercel/path0/.next/server/chunks/9323.js:2894:54)
14:53:32.890 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:53:32.891 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:53:32.891 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:32.891 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:32.891 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
14:53:32.891 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
14:53:32.891 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:32.891 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:53:32.891 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:32.892 |  
14:53:32.892 | Error occurred prerendering page "/category/[category]". Read more: https://nextjs.org/docs/messages/prerender-error
14:53:32.892 | TypeError: Object.assign(...).slice is not a function
14:53:32.892 | at BlogListScroll (/vercel/path0/.next/server/chunks/9323.js:2894:54)
14:53:32.892 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:53:32.892 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:53:32.892 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:32.892 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:32.892 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
14:53:32.892 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
14:53:32.893 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:32.893 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:53:32.893 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

14:53:34.270 | TypeError: Object.assign(...).slice is not a function
14:53:34.270 | at BlogListScroll (/vercel/path0/.next/server/chunks/9323.js:2894:54)
14:53:34.270 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:53:34.270 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:53:34.271 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:34.271 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:34.271 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
14:53:34.271 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
14:53:34.271 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:34.271 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:53:34.271 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:34.273 | TypeError: Object.assign(...).slice is not a function
14:53:34.273 | at BlogListScroll (/vercel/path0/.next/server/chunks/9323.js:2894:54)
14:53:34.273 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
14:53:34.273 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
14:53:34.273 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
14:53:34.273 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:34.273 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
14:53:34.273 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
14:53:34.273 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
14:53:34.273 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
14:53:34.273 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

14:54:01.410 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:54:01.431 | Error: Command "yarn run build" exited with 1
```
```
**相应配置**

**截图**
相关的页面，应该用结果

**环境**
notionNext版本：4.0.2
部署方式：vercel

**Comment by tangly1024** [comment]
感谢反馈，bug已修复，更新即可https://github.com/tangly1024/NotionNext/commit/7579d9c6288a443fdbfd0190aa5bdfcd36614375
