### ISSUE TITLE
主题默认为nobelium时，部署错误

### ISSUE THREAD

**Issue by Wisof-Young** [tangly1024/NotionNext#1376]
**描述遇到的问题**
日志如下：
```
09:10:59.673 | TypeError: posts?.map is not a function
-- | --
09:10:59.673 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.675 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.676 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.680 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.680 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.681 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.681 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.681 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.681 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.681 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.706 |  
09:10:59.706 | Error occurred prerendering page "/category/[category]". Read more: https://nextjs.org/docs/messages/prerender-error
09:10:59.706 | TypeError: posts?.map is not a function
09:10:59.706 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.707 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.707 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.708 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.708 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.708 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.708 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.708 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.708 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.709 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.713 | [缓存]: from:category-props root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.715 | [缓存]: from:category-index-props root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.749 | TypeError: posts?.map is not a function
09:10:59.749 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.749 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.750 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.750 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.750 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.750 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.750 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.750 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.750 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.750 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.750 |  
09:10:59.750 | Error occurred prerendering page "/category/[category]/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
09:10:59.750 | TypeError: posts?.map is not a function
09:10:59.750 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.751 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.751 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.751 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.751 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.751 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.751 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.751 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.751 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.751 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.752 | [缓存]: from:index root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.764 | [缓存]: from:category-page-props root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.769 | [请求API] from:rss-content id:f3868432-f0e2-4251-b872-7121c2d08036
09:10:59.784 | [缓存]: from:category-props root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.794 | TypeError: posts?.map is not a function
09:10:59.794 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.794 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.794 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.794 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.794 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.794 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.794 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.794 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.794 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.794 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.795 |  
09:10:59.795 | Error occurred prerendering page "/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
09:10:59.795 | TypeError: posts?.map is not a function
09:10:59.795 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.795 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.795 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.795 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.795 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.795 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.795 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.795 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.795 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.795 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.797 | [缓存]: from:category-page-props root-page-id:05fd4294d7474b1c800f67437400cca2
09:10:59.800 | TypeError: posts?.map is not a function
09:10:59.800 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.800 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.801 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.801 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.801 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.801 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.801 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.801 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.801 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.801 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.801 |  
09:10:59.801 | Error occurred prerendering page "/search/[keyword]". Read more: https://nextjs.org/docs/messages/prerender-error
09:10:59.801 | TypeError: posts?.map is not a function
09:10:59.801 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.801 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.801 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.802 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.802 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.802 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.802 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.802 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.802 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.802 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.810 | TypeError: posts?.map is not a function
09:10:59.810 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.810 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.810 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.810 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.810 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.810 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.810 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.810 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.810 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.810 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.811 |  
09:10:59.811 | Error occurred prerendering page "/search/[keyword]/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
09:10:59.811 | TypeError: posts?.map is not a function
09:10:59.811 | at BlogListPage (/vercel/path0/.next/server/chunks/9323.js:2828:34)
09:10:59.811 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
09:10:59.811 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
09:10:59.811 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
09:10:59.811 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.812 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.812 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.814 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
09:10:59.814 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
09:10:59.814 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
09:10:59.815 | info  - Generating static pages (15/63)


```

**Comment by tangly1024** [comment]
该 issue 已超过一年没有进一步更新，所涉及的版本、部署环境或第三方服务状态可能已经变化，按过期关闭。若问题仍可在当前最新版本复现，请提交新的 issue，并附上复现步骤、NotionNext 版本、部署平台和相关日志。
