### ISSUE TITLE
设置noage id后执行yarn start 报错

### ISSUE THREAD

**Issue by 2144291529** [tangly1024/NotionNext#1488]
**描述遇到的问题**
报错
yarn start
[root@localhost NotionNext]# NOAGE_ID=07a59d10a6ee44a0a79657e1bdcd76ab
[root@localhost NotionNext]# yarn start 
yarn run v1.22.19
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

Error: Could not find a production build in the '/root/NotionNext/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/root/NotionNext/node_modules/next/dist/server/next-server.js:352:23)
    at new Server (/root/NotionNext/node_modules/next/dist/server/base-server.js:146:29)
    at new NextNodeServer (/root/NotionNext/node_modules/next/dist/server/next-server.js:166:9)
    at NextServer.createServer (/root/NotionNext/node_modules/next/dist/server/next.js:167:24)
    at async /root/NotionNext/node_modules/next/dist/server/next.js:187:31
    at async NextServer.prepare (/root/NotionNext/node_modules/next/dist/server/next.js:149:24)
    at async startServer (/root/NotionNext/node_modules/next/dist/server/lib/start-server.js:269:13)
    at async nextStart (/root/NotionNext/node_modules/next/dist/cli/next-start.js:77:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**相应配置**
 NOAGE_ID=07a59d10a6ee44a0a79657e1bdcd76ab
；本地按照官网vps配置

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/98447108/e6a21037-f523-4d39-a600-8f5b738f4ae3)

**环境**
系统centos7.9

**Comment by tangly1024** [comment]
请按照这个教程操作

https://docs.tangly1024.com/article/deploy-notion-next-on-vps

**Comment by real-jacket** [comment]
本地运行 yarn dev 不要运行 start 。
如果是生产环境启动应用，则先需要构建，先运行 `yarn build`，然后再运行 `yarn start`。
@2144291529 @tangly1024
