### ISSUE TITLE
【部署失败】在vercel上部署，一开始都正常，后面部署就会出现Command "npm run build" exited with 1的报错

### ISSUE THREAD

**Issue by BDTA-zky** [tangly1024/NotionNext#1678]
**描述遇到的问题**
在vercel上部署出现的问题，刚开始几次的部署都没有问题，后来突然就报错了，怎么都部署不上，我把项目删了重新部署，还是这样报错

**Comment by BDTA-zky** [comment]
我不知道怎么上传图片。。。。我把报错复制过来了[18:48:26.106] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[18:48:26.226] Cloning github.com/BDTA-zky/NotionNext (Branch: main, Commit: ac2bb4d)
[18:48:26.236] Skipping build cache, deployment was triggered without cache.
[18:48:26.746] Cloning completed: 519.799ms
[18:48:27.022] Running "vercel build"
[18:48:27.503] Vercel CLI 32.5.6
[18:48:27.920] Installing dependencies...
[18:48:28.983] npm WARN old lockfile 
[18:48:28.984] npm WARN old lockfile The package-lock.json file was created with an old version of npm,
[18:48:28.984] npm WARN old lockfile so supplemental metadata must be fetched from the registry.
[18:48:28.984] npm WARN old lockfile 
[18:48:28.985] npm WARN old lockfile This is a one-time fix-up, please be patient...
[18:48:28.985] npm WARN old lockfile 
[18:48:49.756] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[18:49:05.116] 
[18:49:05.117] added 675 packages in 37s
[18:49:05.117] 
[18:49:05.117] 156 packages are looking for funding
[18:49:05.117]   run `npm fund` for details
[18:49:05.155] Detected Next.js version: 13.3.1
[18:49:05.161] Detected `package-lock.json` generated by npm 7+
[18:49:05.161] Running "npm run build"
[18:49:05.630] 
[18:49:05.630] > notion-next@4.1.1 build
[18:49:05.630] > next build
[18:49:05.631] 
[18:49:05.889] info  - Loaded env from /vercel/path0/.env.local
[18:49:06.027] warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
[18:49:06.028] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[18:49:06.029] 
[18:49:06.043] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[18:49:06.044] This information is used to shape Next.js' roadmap and prioritize features.
[18:49:06.044] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[18:49:06.044] https://nextjs.org/telemetry
[18:49:06.044] 
[18:49:06.166] info  - Linting and checking validity of types...
[18:49:10.275] info  - Creating an optimized production build...
[18:49:10.514] 加载默认主题 /vercel/path0/themes/heo
[18:49:10.544] 加载默认主题 /vercel/path0/themes/heo
[18:49:10.549] 加载默认主题 /vercel/path0/themes/heo
[18:49:39.312] info  - Compiled successfully
[18:49:39.320] info  - Collecting page data...
[18:49:41.258] [请求API] from:slug-paths id:c1ed25f2bc0341779a1cf3a7ca7ef46e 
[18:49:41.283] [请求API] from:slug-paths id:c1ed25f2bc0341779a1cf3a7ca7ef46e 
[18:49:41.359] [请求API] from:slug-paths id:c1ed25f2bc0341779a1cf3a7ca7ef46e 
[18:49:41.387] [请求API] from:category-paths id:c1ed25f2bc0341779a1cf3a7ca7ef46e 
[18:49:42.046] [响应成功]: from:slug-paths
[18:49:42.047] [API耗时] 764ms
[18:49:42.063] [请求API] from:config-table id:86127bc0-f788-4230-a716-ddeebcee109e 
[18:49:42.233] [响应成功]: from:slug-paths
[18:49:42.234] [API耗时] 992ms
[18:49:42.250] [请求API] from:config-table id:86127bc0-f788-4230-a716-ddeebcee109e 
[18:49:42.307] [响应成功]: from:category-paths
[18:49:42.308] [API耗时] 921ms
[18:49:42.322] [请求API] from:config-table id:86127bc0-f788-4230-a716-ddeebcee109e 
[18:49:42.474] [响应成功]: from:slug-paths
[18:49:42.474] [API耗时] 1116ms
[18:49:42.488] [请求API] from:config-table id:86127bc0-f788-4230-a716-ddeebcee109e 
[18:49:42.499] [响应成功]: from:config-table
[18:49:42.499] [API耗时] 250ms
[18:49:42.500] [请求API] from:data-notice id:2f90b9bf-88cd-4681-a24b-803746fd0ca0 
[18:49:42.536] [响应成功]: from:config-table
[18:49:42.537] [API耗时] 473ms
[18:49:42.538] [请求API] from:data-notice id:2f90b9bf-88cd-4681-a24b-803746fd0ca0 
[18:49:42.630] [响应成功]: from:data-notice
[18:49:42.630] [API耗时] 129ms
[18:49:42.640] [缓存]: from:category-paths root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:42.655] [响应成功]: from:data-notice
[18:49:42.656] [API耗时] 119ms
[18:49:42.667] [缓存]: from:page-paths root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:42.679] [缓存]: from:tag-static-path root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:42.684] [缓存]: from:tag-page-static-path root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:43.188] [响应成功]: from:config-table
[18:49:43.188] [API耗时] 866ms
[18:49:43.189] [请求API] from:data-notice id:2f90b9bf-88cd-4681-a24b-803746fd0ca0 
[18:49:43.318] [响应成功]: from:data-notice
[18:49:43.318] [API耗时] 129ms
[18:49:43.710] [响应成功]: from:config-table
[18:49:43.710] [API耗时] 1223ms
[18:49:43.712] [请求API] from:data-notice id:2f90b9bf-88cd-4681-a24b-803746fd0ca0 
[18:49:43.891] [响应成功]: from:data-notice
[18:49:43.891] [API耗时] 179ms
[18:49:55.003] info  - Generating static pages (0/26)
[18:49:55.173] TITLE: NotionNext BLOG
[18:49:55.277] [缓存]: from:404 root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.280] 
[18:49:55.281] Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.281] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/404".
[18:49:55.281] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.281]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.281]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.281]     at Array.every (<anonymous>)
[18:49:55.281]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.282]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.282]     at Array.every (<anonymous>)
[18:49:55.282]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.282]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.282]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.282]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.291] [缓存]: from:archive-index root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.293] 
[18:49:55.293] Error occurred prerendering page "/archive". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.294] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/archive".
[18:49:55.294] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.295]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.295]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.295]     at Array.every (<anonymous>)
[18:49:55.295]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.295]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.295]     at Array.every (<anonymous>)
[18:49:55.295]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.295]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.295]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.295]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.338] TITLE: NotionNext BLOG
[18:49:55.341] TITLE: NotionNext BLOG
[18:49:55.351] TITLE: NotionNext BLOG
[18:49:55.518] [缓存]: from:category-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.521] 
[18:49:55.521] Error occurred prerendering page "/category/日常生活". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.521] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/category/[category]".
[18:49:55.521] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.522]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.522]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.522]     at Array.every (<anonymous>)
[18:49:55.522]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.522]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.522]     at Array.every (<anonymous>)
[18:49:55.522]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.522]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.522]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.523]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.523] info  - Generating static pages (6/26)
[18:49:55.592] TITLE: NotionNext BLOG
[18:49:55.595] TITLE: NotionNext BLOG
[18:49:55.615] [缓存]: from:category-index-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.617] 
[18:49:55.618] Error occurred prerendering page "/category". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.618] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/category".
[18:49:55.618] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.618]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.618]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.618]     at Array.every (<anonymous>)
[18:49:55.618]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.618]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.618]     at Array.every (<anonymous>)
[18:49:55.619]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.619]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.619]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.619]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.619] [缓存]: from:slug-props-links root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.620] info  - Generating static pages (12/26)
[18:49:55.620] [请求API] from:slug-props-links id:f83c6fe7-3a77-4e3e-8670-0e332b2a5a67 
[18:49:55.623] [缓存]: from:index root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.627] 
[18:49:55.627] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.627] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/".
[18:49:55.628] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.628]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.628]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.628]     at Array.every (<anonymous>)
[18:49:55.628]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.628]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.628]     at Array.every (<anonymous>)
[18:49:55.628]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.628]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.629]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.629]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.629] [请求API] from:rss-content id:738f7ba3-a370-4748-bd4f-443bc55526d4 
[18:49:55.635] TITLE: NotionNext BLOG
[18:49:55.653] [缓存]: from:search-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.654] 
[18:49:55.654] Error occurred prerendering page "/search". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.654] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/search".
[18:49:55.654] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.654]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.654]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.655]     at Array.every (<anonymous>)
[18:49:55.655]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.655]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.655]     at Array.every (<anonymous>)
[18:49:55.655]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.655]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.655]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.655]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.658] TITLE: NotionNext BLOG
[18:49:55.667] [缓存]: from:tag-index-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.668] 
[18:49:55.669] Error occurred prerendering page "/tag". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.669] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/tag".
[18:49:55.669] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.669]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.670]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.670]     at Array.every (<anonymous>)
[18:49:55.670]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.670]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.670]     at Array.every (<anonymous>)
[18:49:55.670]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.671]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.671]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.671]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.671] [缓存]: from:slug-props-article/guide root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.672] [请求API] from:slug-props-article/guide id:981ff360-b6d7-43d6-a54f-090df79f0cbd 
[18:49:55.781] [响应成功]: from:rss-content
[18:49:55.789] [API耗时] 154ms
[18:49:55.801] [响应成功]: from:slug-props-article/guide
[18:49:55.801] [API耗时] 128ms
[18:49:55.802] 
[18:49:55.802] Error occurred prerendering page "/article/guide". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.802] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/[prefix]/[slug]".
[18:49:55.802] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.802]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.802]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.802]     at Array.every (<anonymous>)
[18:49:55.802]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.803]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.803]     at Array.every (<anonymous>)
[18:49:55.803]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.803]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.803]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.803]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[18:49:55.803] info  - Generating static pages (19/26)
[18:49:55.805] [缓存]: from:slug-props-article/01 root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.806] [缓存]: from:slug-props-article/01 page_block_738f7ba3-a370-4748-bd4f-443bc55526d4
[18:49:55.807] 
[18:49:55.807] Error occurred prerendering page "/article/01". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.807] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/[prefix]/[slug]".
[18:49:55.807] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.808]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.808]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.808]     at Array.every (<anonymous>)
[18:49:55.808]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.808]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.808]     at Array.every (<anonymous>)
[18:49:55.808]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.808]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.808]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.808]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.814] [缓存]: from:search-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.815] 
[18:49:55.815] Error occurred prerendering page "/search/NotionNext BLOG/page/1". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.815] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/search/[keyword]/page/[page]".
[18:49:55.815] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.816]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.816]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.816]     at Array.every (<anonymous>)
[18:49:55.816]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.816]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.816]     at Array.every (<anonymous>)
[18:49:55.817]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.817]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.817]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.817]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.819] [缓存]: from:tag-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.820] 
[18:49:55.820] Error occurred prerendering page "/tag/日常". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.820] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/tag/[tag]".
[18:49:55.820] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.820]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.820]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.820]     at Array.every (<anonymous>)
[18:49:55.820]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.820]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.821]     at Array.every (<anonymous>)
[18:49:55.821]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.821]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.821]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.821]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:55.892] [响应成功]: from:slug-props-links
[18:49:55.892] [API耗时] 271ms
[18:49:55.893] 
[18:49:55.894] Error occurred prerendering page "/links". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:55.894] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/[prefix]".
[18:49:55.894] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:55.894]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:55.895]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.895]     at Array.every (<anonymous>)
[18:49:55.895]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.895]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:55.895]     at Array.every (<anonymous>)
[18:49:55.895]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:55.895]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:55.896]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:55.896]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[18:49:55.897] [缓存]: from:slug-props-about root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:55.898] [请求API] from:slug-props-about id:7a7a29ca-e982-46f5-9ab2-0dcdc0636ff3 
[18:49:56.018] [响应成功]: from:slug-props-about
[18:49:56.019] [API耗时] 121ms
[18:49:56.019] 
[18:49:56.019] Error occurred prerendering page "/about". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:56.020] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/[prefix]".
[18:49:56.020] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:56.020]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:56.021]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.021]     at Array.every (<anonymous>)
[18:49:56.021]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.021]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.021]     at Array.every (<anonymous>)
[18:49:56.021]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.022]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:56.022]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:56.022]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[18:49:56.023] [缓存]: from:slug-props-# root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:56.024] [缓存]: from:slug-props-# page_block_2f90b9bf-88cd-4681-a24b-803746fd0ca0
[18:49:56.025] 
[18:49:56.025] Error occurred prerendering page "/%23". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:56.025] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/[prefix]".
[18:49:56.025] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:56.025]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:56.026]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.026]     at Array.every (<anonymous>)
[18:49:56.026]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.026]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.026]     at Array.every (<anonymous>)
[18:49:56.026]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.026]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:56.027]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:56.027]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:56.028] [缓存]: from:search-props root-page-id:c1ed25f2bc0341779a1cf3a7ca7ef46e
[18:49:56.032] 
[18:49:56.032] Error occurred prerendering page "/search/NotionNext BLOG". Read more: https://nextjs.org/docs/messages/prerender-error
[18:49:56.032] Error: Error serializing `.NOTION_CONFIG.DESCRIPTION` returned from `getStaticProps` in "/search/[keyword]".
[18:49:56.033] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[18:49:56.033]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:48:19)
[18:49:56.033]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.033]     at Array.every (<anonymous>)
[18:49:56.033]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.033]     at /vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:55:66
[18:49:56.033]     at Array.every (<anonymous>)
[18:49:56.033]     at isSerializable (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:52:39)
[18:49:56.034]     at isSerializableProps (/vercel/path0/node_modules/next/dist/lib/is-serializable-props.js:75:12)
[18:49:56.034]     at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:487:118)
[18:49:56.034]     at async /vercel/path0/node_modules/next/dist/export/worker.js:430:36
[18:49:56.034] 
[18:49:56.034] > Export encountered errors on following paths:
[18:49:56.034] 	/
[18:49:56.034] 	/404
[18:49:56.035] 	/[prefix]/[slug]: /article/01
[18:49:56.035] 	/[prefix]/[slug]: /article/guide
[18:49:56.035] 	/[prefix]: /%23
[18:49:56.035] 	/[prefix]: /about
[18:49:56.035] 	/[prefix]: /links
[18:49:56.035] 	/archive
[18:49:56.035] 	/category
[18:49:56.035] 	/category/[category]: /category/日常生活
[18:49:56.037] 	/search
[18:49:56.037] 	/search/[keyword]/page/[page]: /search/NotionNext BLOG/page/1
[18:49:56.037] 	/search/[keyword]: /search/NotionNext BLOG
[18:49:56.037] 	/tag
[18:49:56.037] 	/tag/[tag]: /tag/日常
[18:49:56.037] info  - Generating static pages (26/26)
[18:49:56.090] Error: Command "npm run build" exited with 1
[18:49:56.610]

**Comment by BDTA-zky** [comment]
解决了

**Comment by tangly1024** [comment]
目前看来，您的代码和Notion模板都是没有问题的，而且在我的电脑上编译正常。你的问题已经解决了吗？


日志中描述的错误，`.NOTION_CONFIG.DESCRIPTION`指的是该配置项没有读取到，通常不会出现该错误，除非代码或者NotionConfig使用不当。
