### ISSUE TITLE
配置中心 config文件添加了几项,vercel部署的时候就出问题了

### ISSUE THREAD

**Issue by niustark** [tangly1024/NotionNext#1800]
**描述遇到的问题**
配置中心 config文件添加了几项,
相应的把代码里的blog.config.js里的配置内容给清了,然后就出问题了

<img width="915" alt="2024-01-24_20-45-55" src="https://github.com/tangly1024/NotionNext/assets/28669447/3296c2a6-ca8f-43fe-84d3-c002f534db10">

简单说明你遇到的问题，相关的日志、错误信息

[20:33:14.616] info  - Generating static pages (0/123)
[20:33:14.861] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:14.861]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:14.862]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:14.862]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:14.862]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:14.862]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:14.862]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:14.862]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:14.862]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:14.862]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:14.863]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:14.867] 
[20:33:14.867] Error occurred prerendering page "/[prefix]/[slug]/[...suffix]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:14.867] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:14.867]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:14.867]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:14.868]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:14.868]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:14.868]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:14.868]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:14.868]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:14.868]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:14.870]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:14.870]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:14.955] [缓存]: from:404 root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.019] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.020]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.020]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.020]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.020]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.020]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.020]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.021]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.023]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.023]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.023]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.024] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.024]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.024]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.024]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.024]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.024]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.024]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.024]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.024]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.025]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.025]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.025] 
[20:33:15.025] Error occurred prerendering page "/[prefix]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.025] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.025]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.025]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.025]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.025]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.026]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.026]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.026]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.026]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.026]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.026]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.032] 
[20:33:15.032] Error occurred prerendering page "/[prefix]/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.032] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.033]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.033]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.033]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.033]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.033]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.033]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.033]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.033]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.033]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.033]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.034] [缓存]: from:slug-props-links root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.043] [请求API] from:slug-props-links id:248ad3fc-4511-44d9-8e16-5511298800e3 
[20:33:15.049] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.050]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.050]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.050]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.050]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.050]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.050]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.050]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.050]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.050]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.051]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.060] 
[20:33:15.060] Error occurred prerendering page "/category/[category]/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.061] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.061]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.061]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.061]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.061]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.061]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.061]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.061]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.062]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.062]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.062]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.069] [缓存]: from:category-index-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.098] [缓存]: from:search-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.159] [缓存]: from:archive-index root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.180] Warning: data for page "/search" is 140 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
[20:33:15.180] See more info here: https://nextjs.org/docs/messages/large-page-data
[20:33:15.236] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.237]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.237]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.237]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.237]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.237]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.238]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.238]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.238]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.238]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.238]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.242] 
[20:33:15.242] Error occurred prerendering page "/tag/[tag]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.242] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.242]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.242]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.243]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.243]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.243]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.243]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.243]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.243]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.243]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.243]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.252] [缓存]: from:tag-index-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.308] [缓存]: from:index root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.362] [缓存]: from:search-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.371] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.371]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.372]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.372]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.372]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.372]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.372]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.372]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.372]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.372]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.373]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.373] 
[20:33:15.373] Error occurred prerendering page "/category/[category]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.373] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.373]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.373]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.374]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.374]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.374]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.374]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.375]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.375]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.375]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.375]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.390] [响应成功]: from:slug-props-links
[20:33:15.390] [API耗时] 347ms
[20:33:15.393] [缓存]: from:category-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.453] [缓存]: from:tag-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.611] [缓存]: from:category-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.681] [缓存]: from:tag-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.699] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.699]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.699]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.700]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.700]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.700]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.700]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.700]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.700]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.700]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.700]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.703] 
[20:33:15.703] Error occurred prerendering page "/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.703] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.703]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.704]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.704]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.704]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.704]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.704]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.704]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.704]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.704]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.705]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.708] [缓存]: from:category-props root-page-id:488d05d7c00b406493685e92b872d6ef
[20:33:15.790] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.791]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.791]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.791]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.791]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.791]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.791]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.791]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.791]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.792]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.792]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[20:33:15.794] 
[20:33:15.794] Error occurred prerendering page "/tag/[tag]/page/[page]". Read more: https://nextjs.org/docs/messages/prerender-error
[20:33:15.794] TypeError: Cannot destructure property 'auth' of 'urlObj' as it is null.
[20:33:15.795]     at formatUrl (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:47:11)
[20:33:15.795]     at formatWithValidation (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/format-url.js:103:12)
[20:33:15.795]     at resolveHref (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/resolve-href.js:22:93)
[20:33:15.795]     at /vercel/path0/.next/server/chunks/2754.js:237:73
[20:33:15.795]     at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
[20:33:15.795]     at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
[20:33:15.795]     at LinkComponent (/vercel/path0/.next/server/chunks/2754.js:229:43)
[20:33:15.795]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[20:33:15.796]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:362)
[20:33:15.798]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

[20:33:23.954] Error: Command "npm run build" exited with 1
[20:33:24.527] 
**相应配置**

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [windows]
- 浏览器 [edge]
- 版本 [120]

**Comment by niustark** [comment]
原因找到了
heo主题配置文件里的 链接内容不能为空,
notion里的config配置了不起作用,还是得在代码里配置NotionNext /themes/heo/config.js

HEO_HERO_TITLE_LINK: 
HEO_INFO_CARD_URL:
