### ISSUE TITLE
切换至 fukasawa 主题时部署至 vercel 错误

### ISSUE THREAD

**Issue by flottant** [tangly1024/NotionNext#181]
vercel报错如下
```
[21:34:50.021] Cloning github.com/flottant/NotionNext (Branch: main, Commit: 36da804)
[21:34:50.428] Cloning completed: 406.739ms
[21:34:50.812] Installing build runtime...
[21:34:54.154] Build runtime installed: 3.341s
[21:34:54.885] Looking up build cache...
[21:34:58.137] Build cache downloaded [61.47 MB]: 2931.458ms
[21:34:58.335] Installing dependencies...
[21:34:58.585] yarn install v1.22.17
[21:34:58.631] info No lockfile found.
[21:34:58.641] [1/4] Resolving packages...
[21:35:12.322] [2/4] Fetching packages...
[21:35:28.153] [3/4] Linking dependencies...
[21:35:28.155] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
[21:35:28.155] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
[21:35:28.156] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[21:35:28.157] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[21:35:28.157] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[21:35:28.157] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[21:35:28.157] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[21:35:28.161] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[21:35:38.012] [4/4] Building fresh packages...
[21:35:38.330] success Saved lockfile.
[21:35:38.336] Done in 39.76s.
[21:35:38.374] Detected Next.js version: 12.1.5
[21:35:38.375] Running "yarn run build"
[21:35:38.649] yarn run v1.22.17
[21:35:38.692] $ next build && next-sitemap --config next-sitemap.config.js
[21:35:39.378] info  - Checking validity of types...
[21:35:41.666] info  - Creating an optimized production build...
[21:36:06.087] info  - Compiled successfully
[21:36:06.087] info  - Collecting page data...
[21:36:06.738] [请求API]: from:slug-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:06.758] [请求API]: from:slug-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:06.774] [请求API]: from:category-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:07.145] [请求成功] from:slug-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:07.164] [请求成功] from:slug-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:07.196] [请求缓存]: from:page-paths root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.204] [请求缓存]: from:tag-static-path root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.221] [请求成功] from:category-paths id:a152bc04c11f401e9d11276673f010cd
[21:36:07.282] info  - Generating static pages (0/24)
[21:36:07.503] [请求缓存]: from:archive-index root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.514] [请求缓存]: from:category-index-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.523] 
[21:36:07.523] Error occurred prerendering page "/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
[21:36:07.523] TypeError: Cannot read property 'description' of undefined
[21:36:07.523]     at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3175:30)
[21:36:07.523]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[21:36:07.523]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[21:36:07.523]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[21:36:07.523]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[21:36:07.523]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[21:36:07.523]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
[21:36:07.523]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
[21:36:07.523]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
[21:36:07.524]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[21:36:07.531] [请求缓存]: from:category-index-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.557] [请求缓存]: from:index root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.580] [请求缓存]: from:search-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.580] info  - Generating static pages (6/24)
[21:36:07.581] 
[21:36:07.581] Error occurred prerendering page "/search/[keyword]". Read more: https://nextjs.org/docs/messages/prerender-error
[21:36:07.581] TypeError: Cannot read property 'description' of undefined
[21:36:07.582]     at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3175:30)
[21:36:07.582]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[21:36:07.582]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[21:36:07.582]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[21:36:07.584]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[21:36:07.584]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[21:36:07.584]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
[21:36:07.584]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
[21:36:07.584]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
[21:36:07.585]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[21:36:07.585] [请求缓存]: from:tag-index-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.585] 
[21:36:07.586] Error occurred prerendering page "/article/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
[21:36:07.586] TypeError: Cannot read property 'description' of undefined
[21:36:07.586]     at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3175:30)
[21:36:07.586]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[21:36:07.586]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[21:36:07.586]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[21:36:07.586]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[21:36:07.586]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[21:36:07.586]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
[21:36:07.586]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
[21:36:07.587]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
[21:36:07.587]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[21:36:07.592] 
[21:36:07.592] Error occurred prerendering page "/tag/[tag]". Read more: https://nextjs.org/docs/messages/prerender-error
[21:36:07.592] TypeError: Cannot read property 'description' of undefined
[21:36:07.592]     at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3175:30)
[21:36:07.592]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[21:36:07.593]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[21:36:07.593]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[21:36:07.593]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[21:36:07.593]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[21:36:07.593]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
[21:36:07.593]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
[21:36:07.593]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
[21:36:07.593]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[21:36:07.595] 
[21:36:07.595] Error occurred prerendering page "/category/[category]". Read more: https://nextjs.org/docs/messages/prerender-error
[21:36:07.595] TypeError: Cannot read property 'description' of undefined
[21:36:07.595]     at AsideLeft (/vercel/path0/.next/server/chunks/399.js:3175:30)
[21:36:07.595]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[21:36:07.595]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[21:36:07.595]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[21:36:07.596]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[21:36:07.596]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[21:36:07.596]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:789:45)
[21:36:07.596]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:393:51)
[21:36:07.596]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:547:20)
[21:36:07.596]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[21:36:07.599] [请求缓存]: from:slug-props-message root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.607] [请求API]: from:slug id:43e32b30-52a6-4a6d-9f53-68c544692acb
[21:36:07.609] [请求缓存]: from:slug-props-links root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.610] info  - Generating static pages (12/24)
[21:36:07.611] [请求缓存]: from:slug-props-example-1 root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.619] [请求API]: from:slug id:2bf71804-262a-4bf5-9ad1-4486a13747d1
[21:36:07.622] [请求API]: from:slug id:9b61f4c6-2a87-457e-8386-09dd904ba5dd
[21:36:07.919] [请求成功] from:slug id:43e32b30-52a6-4a6d-9f53-68c544692acb
[21:36:07.955] [请求成功] from:slug id:2bf71804-262a-4bf5-9ad1-4486a13747d1
[21:36:07.956] [请求缓存]: from:slug-props-example-2 root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.963] [请求API]: from:slug id:a6038582-281a-42d7-8ef7-3d180996f150
[21:36:07.986] [请求缓存]: from:search-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:07.995] 全文搜索缓存 page_block_9b61f4c6-2a87-457e-8386-09dd904ba5dd false
[21:36:07.995] 全文搜索缓存 page_block_a6038582-281a-42d7-8ef7-3d180996f150 false
[21:36:08.011] [请求缓存]: from:tag-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.030] [请求缓存]: from:tag-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.043] [请求缓存]: from:tag-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.061] info  - Generating static pages (18/24)
[21:36:08.062] [请求缓存]: from:tag-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.090] [请求缓存]: from:category-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.108] [请求缓存]: from:category-props root-page-id:a152bc04c11f401e9d11276673f010cd
[21:36:08.268] [请求成功] from:slug id:a6038582-281a-42d7-8ef7-3d180996f150
[21:36:09.773] [请求成功] from:slug id:9b61f4c6-2a87-457e-8386-09dd904ba5dd
[21:36:09.806] {
[21:36:09.806]   youtubeVideoId: null,
[21:36:09.806]   src: 'https://codepen.io/tangly1024/embed/preview/eYeGRRq?default-tabs=html%2Cresult&height=600&host=https%3A%2F%2Fcodepen.io&slug-hash=eYeGRRq',
[21:36:09.806]   format: {
[21:36:09.806]     block_width: 800,
[21:36:09.806]     block_height: 600,
[21:36:09.806]     display_source: 'https://codepen.io/tangly1024/embed/preview/eYeGRRq?default-tabs=html%2Cresult&height=600&host=https%3A%2F%2Fcodepen.io&slug-hash=eYeGRRq',
[21:36:09.806]     block_full_width: false,
[21:36:09.806]     block_page_width: true,
[21:36:09.806]     copied_from_pointer: {
[21:36:09.806]       id: '48c5eacb-362a-4ffa-9b82-8176e6ed1c46',
[21:36:09.806]       table: 'block',
[21:36:09.806]       spaceId: '6c096b44-beb9-48ee-8f92-1efdde47f3a3'
[21:36:09.807]     },
[21:36:09.807]     block_preserve_scale: false
[21:36:09.807]   },
[21:36:09.807]   style: {
[21:36:09.807]     position: 'relative',
[21:36:09.807]     display: 'flex',
[21:36:09.807]     justifyContent: 'center',
[21:36:09.807]     alignSelf: 'center',
[21:36:09.808]     width: '100%',
[21:36:09.808]     maxWidth: '100%',
[21:36:09.808]     flexDirection: 'column',
[21:36:09.808]     height: 600
[21:36:09.808]   }
[21:36:09.808] }
[21:36:09.817] {
[21:36:09.817]   youtubeVideoId: null,
[21:36:09.817]   src: 'https://docs.tangly1024.com/zh',
[21:36:09.817]   format: {
[21:36:09.818]     block_width: 720,
[21:36:09.818]     block_height: 486.99713134765625,
[21:36:09.818]     bookmark_icon: 'https://github.com/favicon.ico',
[21:36:09.818]     bookmark_cover: 'https://opengraph.githubassets.com/7bc91fe7946837cac17c0a6b378f1a80cf14e6eae1e2f0c1dc0f6384826c66ad/tangly1024/NotionNext',
[21:36:09.818]     display_source: 'https://docs.tangly1024.com/zh',
[21:36:09.818]     block_full_width: false,
[21:36:09.818]     block_page_width: true,
[21:36:09.818]     copied_from_pointer: {
[21:36:09.818]       id: '0262365a-23ff-471e-9d94-bd7bfa6bb9fe',
[21:36:09.818]       table: 'block',
[21:36:09.819]       spaceId: '6c096b44-beb9-48ee-8f92-1efdde47f3a3'
[21:36:09.819]     },
[21:36:09.819]     block_preserve_scale: false
[21:36:09.819]   },
[21:36:09.819]   style: {
[21:36:09.819]     position: 'relative',
[21:36:09.819]     display: 'flex',
[21:36:09.819]     justifyContent: 'center',
[21:36:09.819]     alignSelf: 'center',
[21:36:09.819]     width: '100%',
[21:36:09.819]     maxWidth: '100%',
[21:36:09.819]     flexDirection: 'column',
[21:36:09.820]     height: 486.99713134765625
[21:36:09.820]   }
[21:36:09.820] }
[21:36:09.834] info  - Generating static pages (24/24)
[21:36:09.834] 
[21:36:09.835] > Build error occurred
[21:36:09.836] Error: Export encountered errors on following paths:
[21:36:09.836] 	/[slug]
[21:36:09.836] 	/article/[slug]
[21:36:09.836] 	/category/[category]
[21:36:09.836] 	/search/[keyword]
[21:36:09.836] 	/tag/[tag]
[21:36:09.837]     at /vercel/path0/node_modules/next/dist/export/index.js:397:19
[21:36:09.837]     at runMicrotasks (<anonymous>)
[21:36:09.837]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[21:36:09.837]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:36:09.837]     at async /vercel/path0/node_modules/next/dist/build/index.js:1010:17
[21:36:09.837]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:36:09.837]     at async /vercel/path0/node_modules/next/dist/build/index.js:886:13
[21:36:09.837]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[21:36:09.837]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:55:25)
[21:36:09.885] error Command failed with exit code 1.
[21:36:09.886] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[21:36:09.896] Error: Command "yarn run build" exited with 1
```

**Comment by flottant** [comment]
已经找到出错原因。\themes\fukasawa\components\AsideLeft.js 中 第 28 行 siteInfo 应为 SiteInfo。修改后即可成功部署。
```
    <section className='flex flex-col dark:text-gray-300'>
      <hr className='w-12 my-8' />
      { SiteInfo.description }
    </section>
```

**Comment by tangly1024** [comment]
Good~!🎉
