### ISSUE TITLE
自定义配置数据库type字段下的属性名后编译出错

### ISSUE THREAD

**Issue by siuze** [tangly1024/NotionNext#1816]
**描述bug**
自定义配置数据库type字段下的属性名，如“Post”改为“文章”，“Page”改为“页面”后编译出错，无法正确生成tag、category等页面。报错显示应该是某个<link>标签的href属性有问题，我暂时还没定位到具体位置。
编译报错形如：   
```
Error occurred prerendering page "/tag/语法". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.
    at formatUrl (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:47:11)
    at formatWithValidation (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:103:12)
    at resolveHref (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\resolve-href.js:22:93)
    at D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:237:73
    at Object.Kc [as useMemo] (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (D:\pages\notionnext\NotionNext\node_modules\react\cjs\react.production.min.js:25:208)
    at LinkComponent (D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:229:43)
    at Wc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:73:362)
    at Z (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
[缓存]: from:tag-props root-page-id:61b61a8a6a0c4bdd8a5b829e8b01ba68
[ ===] info  - Generating static pages (51/53)TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.
    at formatUrl (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:47:11)
    at formatWithValidation (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:103:12)
    at resolveHref (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\resolve-href.js:22:93)
    at D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:237:73
    at Object.Kc [as useMemo] (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (D:\pages\notionnext\NotionNext\node_modules\react\cjs\react.production.min.js:25:208)
    at LinkComponent (D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:229:43)
    at Wc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:73:362)
    at Z (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)

Error occurred prerendering page "/tag/树嵌入". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.
    at formatUrl (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:47:11)
    at formatWithValidation (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:103:12)
    at resolveHref (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\resolve-href.js:22:93)
    at D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:237:73
    at Object.Kc [as useMemo] (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (D:\pages\notionnext\NotionNext\node_modules\react\cjs\react.production.min.js:25:208)
    at LinkComponent (D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:229:43)
    at Wc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:73:362)
    at Z (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
[缓存]: from:tag-props root-page-id:61b61a8a6a0c4bdd8a5b829e8b01ba68
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.
    at formatUrl (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:47:11)
    at formatWithValidation (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\format-url.js:103:12)
    at resolveHref (D:\pages\notionnext\NotionNext\node_modules\next\dist\shared\lib\router\utils\resolve-href.js:22:93)
    at D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:237:73
    at Object.Kc [as useMemo] (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (D:\pages\notionnext\NotionNext\node_modules\react\cjs\react.production.min.js:25:208)
    at LinkComponent (D:\pages\notionnext\NotionNext\.next\server\chunks\2754.js:229:43)
    at Wc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:73:362)
    at Z (D:\pages\notionnext\NotionNext\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
info  - Generating static pages (53/53)

> Export encountered errors on following paths:
        /
        /404
        /archive
        /category
        /category/[category]: /category/IT技术
        /category/[category]: /category/博观约取
        /category/[category]: /category/碎片杂文
        /category/[category]: /category/言语诗词
        /page/[page]: /page/2
        /page/[page]: /page/3
        /page/[page]: /page/4
        /search
        /search/[keyword]/page/[page]: /search/NotionNext BLOG/page/1
        /search/[keyword]: /search/NotionNext BLOG
        /tag
        /tag/[tag]: /tag/BERT
        /tag/[tag]: /tag/C4.5
        /tag/[tag]: /tag/ID3
        /tag/[tag]: /tag/Python
        /tag/[tag]: /tag/TCGA
        /tag/[tag]: /tag/上下文
        /tag/[tag]: /tag/主成分
        /tag/[tag]: /tag/决策树
        /tag/[tag]: /tag/可视化
        /tag/[tag]: /tag/癌症基因
        /tag/[tag]: /tag/论文阅读
        /tag/[tag]: /tag/词义
        /tag/[tag]: /tag/语法
        /tag/[tag]: /tag/课程作业
        /tag/[tag]: /tag/鱼类
```

**复现步骤**
修改配置文件：
```
  NOTION_PROPERTY_NAME: {
    type_post: process.env.NEXT_PUBLIC_NOTION_PROPERTY_TYPE_POST || '文章', // 当type文章类型与此值相同时，为博文。
    type_page: process.env.NEXT_PUBLIC_NOTION_PROPERTY_TYPE_PAGE || '页面', // 当type文章类型与此值相同时，为单页。
    type_notice:
          process.env.NEXT_PUBLIC_NOTION_PROPERTY_TYPE_NOTICE || '公告', // 当type文章类型与此值相同时，为公告。
    type_menu: process.env.NEXT_PUBLIC_NOTION_PROPERTY_TYPE_MENU || '菜单', // 当type文章类型与此值相同时，为菜单。
    type_sub_menu:
          process.env.NEXT_PUBLIC_NOTION_PROPERTY_TYPE_SUB_MENU || '子菜单', // 当type文章类型与此值相同时，为子菜单。
  },
```
同时一并修改Notion数据库内的字段可选值为中文，之后执行 `yarn build` ，即出现报错如上方日志所示。   
  
**期望的正常结果**
正常编译通过

**环境**

- 【必填】NotionNext版本   Jan 25, 2024的commit
- 【必填】主题 hexo
- 【可选】操作系统: windows
- 【可选】浏览器 chrome

**补充说明**
自定义修改slug字段名时也有问题，我会另外发一个issue

**Comment by siuze** [comment]
还有一个问题，自定义属性Menu为其他名称后，网页上方的导航栏菜单会消失（看来这个自定义功能目前有好多问题啊）
