### ISSUE TITLE
从4.2.1升级到4.4.2部署更新失败

### ISSUE THREAD

**Issue by wilfzhao** [tangly1024/NotionNext#2246]
从4.2.1升级到4.4.2部署更新失败。网页可以正常打开，但版本号还是旧的4.2.1，Vercel部署失败

<img width="1248" alt="image" src="https://github.com/tangly1024/NotionNext/assets/48481525/17f3f911-e21c-4b0c-b90a-d6612aeb8001">

- 操作系统: [macOS Sonoma 14.4]
- 浏览器 [chrome]

**Comment by momeigui** [comment]
我的版本号是正常了,但修改任何配置都会提示这个
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
11:16:58.431 |  
11:16:58.431 | > Build error occurred
11:16:58.433 | ReferenceError: ture is not defined
11:16:58.433 | at Object.<anonymous> (/vercel/path0/blog.config.js:21:55)
11:16:58.433 | at Module._compile (node:internal/modules/cjs/loader:1356:14)
11:16:58.433 | at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
11:16:58.433 | at Module.load (node:internal/modules/cjs/loader:1197:32)
11:16:58.434 | at Module._load (node:internal/modules/cjs/loader:1013:12)
11:16:58.434 | at Module.require (node:internal/modules/cjs/loader:1225:19)
11:16:58.434 | at require (node:internal/modules/helpers:177:18)
11:16:58.434 | at Object.<anonymous> (/vercel/path0/next.config.js:1:19)
11:16:58.434 | at Module._compile (node:internal/modules/cjs/loader:1356:14)
11:16:58.434 | at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
11:16:58.450 | error Command failed with exit code 1.
11:16:58.450 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:16:58.466 | Error: Command "yarn run build" exited with 1
11:16:58.797
