### ISSUE TITLE
【页面报错】添加gittalk后首页正常但点进文章报错client-side-exception-occurred

### ISSUE THREAD

**Issue by tubehao** [tangly1024/NotionNext#2303]
**描述遇到的问题**
> 添加gittalk后首页正常但点进文章报错
Third-party cookie will be blocked. Learn more in the Issues tab.
_app-b6039335e6b283eb.js:1 Load Success https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
_app-b6039335e6b283eb.js:1 Load Success /js/custom.js
_app-b6039335e6b283eb.js:1 Load Success /css/custom.css
_app-b6039335e6b283eb.js:1 Load Success https://cdn.bootcdn.net/ajax/libs/aos/2.3.4/aos.css
_app-b6039335e6b283eb.js:1 Load Success https://cdn.bootcdn.net/ajax/libs/nprogress/0.2.0/nprogress.min.js
9<link rel=preload> has an invalid `href` value
_app-b6039335e6b283eb.js:1 Load Success https://cdn.bootcdn.net/ajax/libs/nprogress/0.2.0/nprogress.min.css
_app-b6039335e6b283eb.js:1 Load Success https://cdn.bootcdn.net/ajax/libs/aos/2.3.4/aos.js
_app-b6039335e6b283eb.js:1 Load Success https://cdn.jsdelivr.net/npm/typed.js@2.0.12
live2d.min.js:1 Live2D 2.1.00_1
live2d.min.js:1 profile : Desktop
live2d.min.js:1   [PROFILE_NAME] = Desktop
live2d.min.js:1   [USE_ADJUST_TRANSLATION] = false
live2d.min.js:1   [USE_CACHED_POLYGON_IMAGE] = false
live2d.min.js:1   [EXPAND_W] = 2
_app-b6039335e6b283eb.js:1 Load Success https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/live2d.min.js
_app-b6039335e6b283eb.js:1 Load Success https://npm.elemecdn.com/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js
_app-b6039335e6b283eb.js:1 Load Success https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-solarizedlight.css
_app-b6039335e6b283eb.js:1 Load Success /css/prism-mac-style.css
live2d.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at r.hitTestSimpleCustom (live2d.min.js:1:5284)
    at o.hitTestCustom (live2d.min.js:1:146877)
    at o.tapEvent (live2d.min.js:1:137689)
    at p (live2d.min.js:1:22319)
    at g (live2d.min.js:1:22887)
framework-75746eeb80cbf23f.js:9 TypeError: Cannot read properties of null (reading 'split')
    at r (6180.dafa1ee802a2c698.js:1:444)
    at ab (framework-75746eeb80cbf23f.js:9:60917)
    at i (framework-75746eeb80cbf23f.js:9:119475)
    at oO (framework-75746eeb80cbf23f.js:9:99114)
    at framework-75746eeb80cbf23f.js:9:98981
    at oF (framework-75746eeb80cbf23f.js:9:98988)
    at ox (framework-75746eeb80cbf23f.js:9:95740)
    at oC (framework-75746eeb80cbf23f.js:9:96129)
    at r4 (framework-75746eeb80cbf23f.js:9:44778)
    at framework-75746eeb80cbf23f.js:9:93632
a5 @ framework-75746eeb80cbf23f.js:9
main-6f168ed21cbf16ac.js:1 TypeError: Cannot read properties of null (reading 'split')
    at r (6180.dafa1ee802a2c698.js:1:444)
    at ab (framework-75746eeb80cbf23f.js:9:60917)
    at i (framework-75746eeb80cbf23f.js:9:119475)
    at oO (framework-75746eeb80cbf23f.js:9:99114)
    at framework-75746eeb80cbf23f.js:9:98981
    at oF (framework-75746eeb80cbf23f.js:9:98988)
    at ox (framework-75746eeb80cbf23f.js:9:95740)
    at oC (framework-75746eeb80cbf23f.js:9:96129)
    at r4 (framework-75746eeb80cbf23f.js:9:44778)
    at framework-75746eeb80cbf23f.js:9:93632
Z @ main-6f168ed21cbf16ac.js:1
main-6f168ed21cbf16ac.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-6f168ed21cbf16ac.js:1
live2d.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at r.hitTestSimpleCustom (live2d.min.js:1:5284)
    at o.hitTestCustom (live2d.min.js:1:146877)
    at o.tapEvent (live2d.min.js:1:137689)
    at p (live2d.min.js:1:22319)
    at g (live2d.min.js:1:22887)
6180.dafa1ee802a2c698.js:1 Uncaught TypeError: Cannot read properties of null (reading 'split')
    at r (6180.dafa1ee802a2c698.js:1:444)
    at ab (framework-75746eeb80cbf23f.js:9:60917)
    at i (framework-75746eeb80cbf23f.js:9:119475)
    at oO (framework-75746eeb80cbf23f.js:9:99114)
    at framework-75746eeb80cbf23f.js:9:98981
    at oF (framework-75746eeb80cbf23f.js:9:98988)
    at oC (framework-75746eeb80cbf23f.js:9:96074)
    at r4 (framework-75746eeb80cbf23f.js:9:44778)
    at framework-75746eeb80cbf23f.js:9:93632
framework-75746eeb80cbf23f.js:9 TypeError: Cannot read properties of null (reading 'split')
    at r (6180.dafa1ee802a2c698.js:1:444)
    at ab (framework-75746eeb80cbf23f.js:9:60917)
    at i (framework-75746eeb80cbf23f.js:9:119475)
    at oO (framework-75746eeb80cbf23f.js:9:99114)
    at framework-75746eeb80cbf23f.js:9:98981
    at oF (framework-75746eeb80cbf23f.js:9:98988)
    at ox (framework-75746eeb80cbf23f.js:9:95740)
    at oC (framework-75746eeb80cbf23f.js:9:96129)
    at r4 (framework-75746eeb80cbf23f.js:9:44778)
    at framework-75746eeb80cbf23f.js:9:93632
a5 @ framework-75746eeb80cbf23f.js:9
main-6f168ed21cbf16ac.js:1 TypeError: Cannot read properties of null (reading 'split')
    at r (6180.dafa1ee802a2c698.js:1:444)
    at ab (framework-75746eeb80cbf23f.js:9:60917)
    at i (framework-75746eeb80cbf23f.js:9:119475)
    at oO (framework-75746eeb80cbf23f.js:9:99114)
    at framework-75746eeb80cbf23f.js:9:98981
    at oF (framework-75746eeb80cbf23f.js:9:98988)
    at ox (framework-75746eeb80cbf23f.js:9:95740)
    at oC (framework-75746eeb80cbf23f.js:9:96129)
    at r4 (framework-75746eeb80cbf23f.js:9:44778)
    at framework-75746eeb80cbf23f.js:9:93632
Z @ main-6f168ed21cbf16ac.js:1
main-6f168ed21cbf16ac.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**相应配置**
网址：https://tubehao.vercel.app/
notion page id: 7514985b76754b3fb55ee1540b7894ce

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/113823954/c3371412-4d9f-47b8-a1c1-2f17a73adc3d)
**环境**

- 操作系统: windows
- 浏览器 chrome
- 版本 最新版

**Comment by tangly1024** [comment]
目前看似乎是正常了，问题解决了吗？

**Comment by Phillweston** [comment]
该问题应该跟gittalk无关

**Comment by Phillweston** [comment]
看了一下代码，应该是removeChild和insertBefore函数调用的时候，而该节点不是试图插入前的父节点的子节点时抛出的。我看代码中没有做这部分判断，我推了一个PR过去，应该能修复该问题。

https://github.com/tangly1024/NotionNext/pull/2417

**Comment by FormatToday** [comment]
好像还有这个问题，我刚弄的不行

**Comment by LisnXy** [comment]
同样的问题还在发生，
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by tangly1024** [comment]
该 issue 已超过一年没有进一步更新，所涉及的版本、部署环境或第三方服务状态可能已经变化，按过期关闭。若问题仍可在当前最新版本复现，请提交新的 issue，并附上复现步骤、NotionNext 版本、部署平台和相关日志。
