### ISSUE TITLE
部署后偶发性502错误

### ISSUE THREAD

**Issue by dragon-fish** [tangly1024/NotionNext#2560]
**描述bug**

RT，有时候是整个页面 502，有时候是某个 API 调用时 502。

![image](https://github.com/tangly1024/NotionNext/assets/44761872/cb29bd9c-a645-44f0-9918-8aad6ce88967)

检查 Next.js Functions 日志发现如下报错，供参考：

```
ERROR  Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot convert argument to a ByteString because the character at index 13 has a value of 28909 which is greater than 255.","stack":["TypeError: Cannot convert argument to a ByteString because the character at index 13 has a value of 28909 which is greater than 255.","    at webidl.converters.ByteString (node:internal/deps/undici/undici:1985:17)","    at _Headers.set (node:internal/deps/undici/undici:3344:35)","    at setCacheTagsHeaders (file:///var/task/.netlify/dist/run/headers.js:183:13)","    at file:///var/task/.netlify/dist/run/handlers/server.js:3165:5","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async server_default (file:///var/task/.netlify/dist/run/handlers/server.js:3137:10)","    at async file:///var/task/___netlify-server-handler.mjs:31:24","    at async Module.handler (file:///var/task/___netlify-server-handler.mjs:19:27)","    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:2:26296)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)"]}
```

Trace:
```
TypeError: Cannot convert argument to a ByteString because the character at index 13 has a value of 28909 which is greater than 255.
    at webidl.converters.ByteString (node:internal/deps/undici/undici:1985:17)
    at _Headers.set (node:internal/deps/undici/undici:3344:35)
    at setCacheTagsHeaders (file:///var/task/.netlify/dist/run/headers.js:183:13)
    at file:///var/task/.netlify/dist/run/handlers/server.js:3165:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async server_default (file:///var/task/.netlify/dist/run/handlers/server.js:3137:10)
    at async file:///var/task/___netlify-server-handler.mjs:31:24
    at async Module.handler (file:///var/task/___netlify-server-handler.mjs:19:27)
    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:2:26296)
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)
```

**期望的正常结果**

正常访问

**复现步骤**

-

**环境**

- 【必填】NotionNext版本 4.6.1
- 【必填】主题 heo
- 【必填】部署方案 netlify
- 【可选】操作系统: all
- 【可选】浏览器 Edge, Safari

**补充说明**

- Notion Database: https://epbureau.notion.site/2b6a4d67f9e94df2b117047e0668070e
- Website: https://archive.epb.wiki

**Comment by matyle** [comment]
同样遇到这个问题

**Comment by tangly1024** [comment]
该 issue 已超过一年没有进一步更新，所涉及的版本、部署环境或第三方服务状态可能已经变化，按过期关闭。若问题仍可在当前最新版本复现，请提交新的 issue，并附上复现步骤、NotionNext 版本、部署平台和相关日志。
