### ISSUE TITLE
【Page_ID错误】无法编译Error: Command "yarn run build" exited with 1

### ISSUE THREAD

**Issue by yeahooool** [tangly1024/NotionNext#2570]
**描述遇到的问题**
vercel上部署失败

**相应配置**
仅设置NOTION_PAGE_ID: 969b3f96f07e48428c60cde838434a20
notion页面：https://yeaho.notion.site/Openspace-969b3f96f07e48428c60cde838434a20
![image](https://github.com/tangly1024/NotionNext/assets/76612689/e50c3503-f106-4c50-b7fa-75fefa59a5e3)

**截图**
![image](https://github.com/tangly1024/NotionNext/assets/76612689/5f0fe9ae-76a6-4f9d-9793-d0b35aaddc1e)
![image](https://github.com/tangly1024/NotionNext/assets/76612689/623bdee8-e762-4fb5-adeb-c7d66b47e7db)
![image](https://github.com/tangly1024/NotionNext/assets/76612689/7dbbe6d5-765e-4586-978d-e089d013dd6a)

**环境**

- 操作系统:  windows
- 浏览器 edge
- 版本 4.6.1

**Comment by yeahooool** [comment]
完整log如下：
[17:41:59.608] Running build in Washington, D.C., USA (East) – iad1
[17:41:59.868] Cloning github.com/yeahooool/NotionNext (Branch: main, Commit: 4535dec)
[17:41:59.932] Skipping build cache, deployment was triggered without cache.
[17:42:00.772] Cloning completed: 901.201ms
[17:42:01.528] Running "vercel build"
[17:42:01.979] Vercel CLI 34.2.8
[17:42:02.444] Installing dependencies...
[17:42:02.760] yarn install v1.22.19
[17:42:02.838] [1/4] Resolving packages...
[17:42:03.095] [2/4] Fetching packages...
[17:42:29.491] [3/4] Linking dependencies...
[17:42:29.497] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[17:42:29.498] warning "react-notion-x > react-image@4.1.0" has unmet peer dependency "@babel/runtime@>=7".
[17:42:29.498] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[17:42:29.500] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[17:42:29.501] warning "react-notion-x > react-lazy-images > react-intersection-observer@6.4.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
[17:42:29.501] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[17:42:29.503] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > ts-api-utils@1.0.3" has unmet peer dependency "typescript@>=4.2.0".
[17:42:29.503] warning " > eslint-plugin-prettier@5.1.3" has incorrect peer dependency "eslint@>=8.0.0".
[17:42:36.062] [4/4] Building fresh packages...
[17:42:36.802] Done in 34.05s.
[17:42:36.889] Detected Next.js version: 14.2.4
[17:42:36.892] Running "yarn run build"
[17:42:37.076] yarn run v1.22.19
[17:42:37.117] $ next build
[17:42:38.453] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:42:38.453] This information is used to shape Next.js' roadmap and prioritize features.
[17:42:38.454] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:42:38.454] https://nextjs.org/telemetry
[17:42:38.454] 
[17:42:38.517]   ▲ Next.js 14.2.4
[17:42:38.517]   - Environments: .env.local
[17:42:38.517]   - Experiments (use with caution):
[17:42:38.517]     · scrollRestoration
[17:42:38.517] 
[17:42:38.518]    Linting and checking validity of types ...
[17:42:42.035]    Creating an optimized production build ...
[17:42:42.231] [默认主题] /vercel/path0/themes/simple
[17:43:15.031]  ✓ Compiled successfully
[17:43:15.032]    Collecting page data ...
[17:43:15.601] [Fetching Data] 969b3f96f07e48428c60cde838434a20 slug-paths
[17:43:15.601] [API-->>请求] from:slug-paths id:969b3f96f07e48428c60cde838434a20 
[17:43:17.298] [API<<--响应] 耗时:1692ms - from:slug-paths
[17:43:17.304] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.308] [Fetching Data] 969b3f96f07e48428c60cde838434a20 slug-paths
[17:43:17.309] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.312] [Fetching Data] 969b3f96f07e48428c60cde838434a20 slug-paths
[17:43:17.313] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.322] [Fetching Data] 969b3f96f07e48428c60cde838434a20 category-paths
[17:43:17.322] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.327] [Fetching Data] 969b3f96f07e48428c60cde838434a20 category-paths
[17:43:17.328] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.352] [Fetching Data] 969b3f96f07e48428c60cde838434a20 page-paths
[17:43:17.353] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.376] [Fetching Data] 969b3f96f07e48428c60cde838434a20 tag-static-path
[17:43:17.377] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:17.379] [Fetching Data] 969b3f96f07e48428c60cde838434a20 tag-page-static-path
[17:43:17.379] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:20.324]    Generating static pages (0/42) ...
[17:43:20.603] missing block undefined
[17:43:20.814] missing block undefined
[17:43:20.898] missing block undefined
[17:43:21.362]    Generating static pages (10/42) 
[17:43:21.484] [Fetching Data] 969b3f96f07e48428c60cde838434a20 slug-props-13a171332816461db29d50e9f575b00d
[17:43:21.485] [API-->>请求] from:slug-props-13a171332816461db29d50e9f575b00d id:1 
[17:43:21.485] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:21.485] [API<<--异常]: TypeError: e.split is not a function
[17:43:21.485]     at W (file:///vercel/path0/node_modules/notion-client/node_modules/notion-utils/build/index.js:1:4766)
[17:43:21.485]     at E.getPageRaw (file:///vercel/path0/node_modules/notion-client/build/index.js:1:2806)
[17:43:21.485]     at E.getPage (file:///vercel/path0/node_modules/notion-client/build/index.js:1:527)
[17:43:21.485]     at d (/vercel/path0/.next/server/chunks/36362.js:2:12346)
[17:43:21.485]     at u (/vercel/path0/.next/server/chunks/36362.js:2:11968)
[17:43:21.486]     at async _ (/vercel/path0/.next/server/chunks/20158.js:2:4271)
[17:43:21.486]     at async e3 (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3907)
[17:43:21.486]     at async exportPages (/vercel/path0/node_modules/next/dist/export/routes/pages.js:84:28)
[17:43:21.486]     at async exportPageImpl (/vercel/path0/node_modules/next/dist/export/worker.js:205:16)
[17:43:21.487]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:154:20)
[17:43:22.665] [API-->>请求] from:slug-props-13a171332816461db29d50e9f575b00d id:1 剩余重试次数:2
[17:43:22.666] [API<<--异常]: TypeError: e.split is not a function
[17:43:22.666]     at W (file:///vercel/path0/node_modules/notion-client/node_modules/notion-utils/build/index.js:1:4766)
[17:43:22.666]     at E.getPageRaw (file:///vercel/path0/node_modules/notion-client/build/index.js:1:2806)
[17:43:22.666]     at E.getPage (file:///vercel/path0/node_modules/notion-client/build/index.js:1:527)
[17:43:22.666]     at d (/vercel/path0/.next/server/chunks/36362.js:2:12346)
[17:43:22.666]     at d (/vercel/path0/.next/server/chunks/36362.js:2:12574)
[17:43:22.666]     at async u (/vercel/path0/.next/server/chunks/36362.js:2:11962)
[17:43:22.667]     at async _ (/vercel/path0/.next/server/chunks/20158.js:2:4271)
[17:43:22.667]     at async e3 (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3907)
[17:43:22.667]     at async exportPages (/vercel/path0/node_modules/next/dist/export/routes/pages.js:84:28)
[17:43:22.667]     at async exportPageImpl (/vercel/path0/node_modules/next/dist/export/worker.js:205:16)
[17:43:23.481] [API-->>请求] from:slug-props-13a171332816461db29d50e9f575b00d id:1 剩余重试次数:1
[17:43:23.482] [API<<--异常]: TypeError: e.split is not a function
[17:43:23.482]     at W (file:///vercel/path0/node_modules/notion-client/node_modules/notion-utils/build/index.js:1:4766)
[17:43:23.482]     at E.getPageRaw (file:///vercel/path0/node_modules/notion-client/build/index.js:1:2806)
[17:43:23.483]     at E.getPage (file:///vercel/path0/node_modules/notion-client/build/index.js:1:527)
[17:43:23.483]     at d (/vercel/path0/.next/server/chunks/36362.js:2:12346)
[17:43:23.483]     at d (/vercel/path0/.next/server/chunks/36362.js:2:12574)
[17:43:23.483]     at async d (/vercel/path0/.next/server/chunks/36362.js:2:12568)
[17:43:23.483]     at async u (/vercel/path0/.next/server/chunks/36362.js:2:11962)
[17:43:23.483]     at async _ (/vercel/path0/.next/server/chunks/20158.js:2:4271)
[17:43:23.484]     at async e3 (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3907)
[17:43:23.484]     at async exportPages (/vercel/path0/node_modules/next/dist/export/routes/pages.js:84:28)
[17:43:24.426] [请求失败]: from:slug-props-13a171332816461db29d50e9f575b00d id:1
[17:43:24.427] TypeError: Cannot read properties of null (reading 'block')
[17:43:24.427]     at NotionBlockRenderer (file:///vercel/path0/node_modules/react-notion-x/build/index.js:2706:47)
[17:43:24.427]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[17:43:24.427]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[17:43:24.427]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.427]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
[17:43:24.427]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.427]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
[17:43:24.427]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.427]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
[17:43:24.428]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.428] 
[17:43:24.428] Error occurred prerendering page "/zh/13a171332816461db29d50e9f575b00d". Read more: https://nextjs.org/docs/messages/prerender-error
[17:43:24.428] 
[17:43:24.428] TypeError: Cannot read properties of null (reading 'block')
[17:43:24.428]     at NotionBlockRenderer (file:///vercel/path0/node_modules/react-notion-x/build/index.js:2706:47)
[17:43:24.428]     at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
[17:43:24.428]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
[17:43:24.428]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.428]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
[17:43:24.428]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.428]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
[17:43:24.428]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.428]     at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
[17:43:24.428]     at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
[17:43:24.466] [Fetching Data] 969b3f96f07e48428c60cde838434a20 search-props
[17:43:24.466] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:24.825] [Fetching Data] 969b3f96f07e48428c60cde838434a20 search-props
[17:43:24.826] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:24.982] [Fetching Data] 969b3f96f07e48428c60cde838434a20 404
[17:43:24.982] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.027] [Fetching Data] 969b3f96f07e48428c60cde838434a20 404
[17:43:25.028] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.084] missing block undefined
[17:43:25.148] missing block undefined
[17:43:25.184] missing block undefined
[17:43:25.203] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.204] [Fetching Data] 969b3f96f07e48428c60cde838434a20 archive-index
[17:43:25.225]    Generating static pages (20/42) 
[17:43:25.257] [Fetching Data] 969b3f96f07e48428c60cde838434a20 archive-index
[17:43:25.258] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.398] [Fetching Data] 969b3f96f07e48428c60cde838434a20 category-index-props
[17:43:25.398] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.443] [Fetching Data] 969b3f96f07e48428c60cde838434a20 category-index-props
[17:43:25.443] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.495] [Fetching Data] 969b3f96f07e48428c60cde838434a20 index
[17:43:25.495] [RSS订阅] 生成/rss/feed.xml
[17:43:25.496] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.704] [Fetching Data] 969b3f96f07e48428c60cde838434a20 index
[17:43:25.706] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.927] [Fetching Data] 969b3f96f07e48428c60cde838434a20 search-props
[17:43:25.928]    Generating static pages (31/42) 
[17:43:25.928] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:25.961] [Fetching Data] 969b3f96f07e48428c60cde838434a20 search-props
[17:43:25.962] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.130] [Fetching Data] 969b3f96f07e48428c60cde838434a20 SignIn
[17:43:26.131] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.131] missing block undefined
[17:43:26.215] [Fetching Data] 969b3f96f07e48428c60cde838434a20 SignIn
[17:43:26.215] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.215] missing block undefined
[17:43:26.246] [Fetching Data] 969b3f96f07e48428c60cde838434a20 SignIn
[17:43:26.247] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.247] missing block undefined
[17:43:26.662] [Fetching Data] 969b3f96f07e48428c60cde838434a20 SignIn
[17:43:26.662] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.663] missing block undefined
[17:43:26.833] [Fetching Data] 969b3f96f07e48428c60cde838434a20 tag-index-props
[17:43:26.834] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.878] [Fetching Data] 969b3f96f07e48428c60cde838434a20 tag-index-props
[17:43:26.878] pageId "969b3f96-f07e-4842-8c60-cde838434a20" is not a database
[17:43:26.926]  ✓ Generating static pages (42/42)
[17:43:26.936] 
[17:43:26.941] > Export encountered errors on following paths:
[17:43:26.941] 	/[prefix]: /zh/13a171332816461db29d50e9f575b00d
[17:43:27.003] error Command failed with exit code 1.
[17:43:27.003] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[17:43:27.025] Error: Command "yarn run build" exited with 1
[17:43:27.404]
