### ISSUE TITLE
Vercel部署时报错blog.config.js

### ISSUE THREAD

**Issue by zsrlukezhang** [tangly1024/NotionNext#2588]
**描述遇到的问题**
在Vercel平台上部署时，报错：
```
/vercel/path0/blog.config.js:13
  APPEARANCE: process.env.NEXT_PUBLIC_APPEARANCE || 'light', // ['light', 'dark', 'auto'], // light 日间模式 ， dark夜间模式， auto根据时间和主题自动夜间模式
            ^
SyntaxError: Unexpected token ':'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at mod.require (/vercel/path0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/vercel/path0/next.config.js:1:19)
error Command failed with exit code 1.
```
同时，`APPEARANCE: `在GitHub的代码预览中显示为黑色而非墨蓝色。
删除 `APPEARANCE: `后部署成功。

**相应配置**
Page ID: `f69cea58e7b3427294cff40461dc5fd8`
网站地址：lukezhang.win

**截图**
![image](https://github.com/user-attachments/assets/e529b712-3960-48ae-a5bc-a8fb4024defd)

**环境**

- 操作系统: [Microsoft Windows 11]
- 浏览器 [Edge/Chrome]
- 版本 [什么意思？没看懂]

**Comment by tangly1024** [comment]
该 issue 已超过一年没有进一步更新，所涉及的版本、部署环境或第三方服务状态可能已经变化，按过期关闭。若问题仍可在当前最新版本复现，请提交新的 issue，并附上复现步骤、NotionNext 版本、部署平台和相关日志。
