### ISSUE TITLE
[部署失败] 编辑blog.config.js后部署失败

### ISSUE THREAD

**Issue by lhtlikeAyaka** [tangly1024/NotionNext#2601]
**描述bug**
错误提示
> Build error occurred
/vercel/path0/blog.config.js:29
  LINK: process.env.NEXT_PUBLIC_LINK || 'https://lhtblog.us.kg // 网站地址
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at mod.require (/vercel/path0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/vercel/path0/next.config.js:1:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
**期望的正常结果**
可以正常部署

**复现步骤**
按照教程部署

**环境**

- 【必填】NotionNext版本 4.6.1
- 【必填】主题 next
- 【必填】部署方案 vercel和cloudflare
- 【可选】操作系统: macOS
- 【可选】浏览器 chrome

**Comment by ymh0000123** [comment]
哥们 你后面的单引号被你删除了
## 错误的
    LINK: process.env.NEXT_PUBLIC_LINK || 'https://lhtblog.us.kg/ // 网站地址
## 正确的
    LINK: process.env.NEXT_PUBLIC_LINK || 'https://lhtblog.us.kg/' // 网站地址

**Comment by tangly1024** [comment]
该 issue 已标记为 resolved，按已解决关闭。若问题仍可在最新版本复现，请重新开启或提交新的 issue，并附上复现步骤与版本信息。
