### ISSUE TITLE
[部署失败] 编辑blog.config.js后部署失败

### ISSUE THREAD

**Issue by RoRyou** [tangly1024/NotionNext#2698]
**描述遇到的问题**
想关rss的，后来没有成功，然后想恢复，恢复不了了。

简单说明你遇到的问题，相关的日志、错误信息

[11:32:03.531] Running build in Washington, D.C., USA (East) – iad1
[11:32:04.465] Cloning github.com/RoRyou/NotionNext (Branch: main, Commit: 0d2ef4d)
[11:32:05.835] Cloning completed: 1.360s
[11:32:13.311] Restored build cache
[11:32:13.468] Running "vercel build"
[11:32:14.486] Vercel CLI 37.1.2
[11:32:15.388] Installing dependencies...
[11:32:15.976] yarn install v1.22.19
[11:32:16.172] [1/4] Resolving packages...
[11:32:16.835] success Already up-to-date.
[11:32:16.852] Done in 0.89s.
[11:32:16.878] Detected Next.js version: 14.2.4
[11:32:16.884] Running "yarn run build"
[11:32:17.323] yarn run v1.22.19
[11:32:17.431] $ next build
[11:32:19.963]   ▲ Next.js 14.2.4
[11:32:19.964]   - Environments: .env.local
[11:32:19.964]   - Experiments (use with caution):
[11:32:19.964]     · scrollRestoration
[11:32:19.965] 
[11:32:19.965]    Linting and checking validity of types ...
[11:32:26.348]    Creating an optimized production build ...
[11:32:26.548] [默认主题] /vercel/path0/themes/simple
[11:32:42.682] Browserslist: caniuse-lite is outdated. Please run:
[11:32:42.682]   npx update-browserslist-db@latest
[11:32:42.682]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[11:33:00.606]  ✓ Compiled successfully
[11:33:00.608]    Collecting page data ...
[11:33:01.004] [Fetching Data] e188f2d698444181bc05167c021827ef slug-paths
[11:33:01.005] [API-->>请求] from:slug-paths id:e188f2d698444181bc05167c021827ef 
[11:33:05.553] [API<<--响应] 耗时:644ms - from:slug-paths
[11:33:05.579] [API-->>请求] from:config-table id:d1bb80e6-b5a8-47ab-a380-a9cb5235222a 
[11:33:05.858] [API<<--响应] 耗时:276ms - from:config-table
[11:33:05.859] [API-->>请求] from:data-notice id:2508834e-ad39-40e9-a6a4-c8000dfa5ac3 
[11:33:05.992] [API<<--响应] 耗时:132ms - from:data-notice
[11:33:09.274]    Generating static pages (0/79) ...
[11:33:09.564] missing block undefined
[11:33:09.743] missing block undefined
[11:33:09.813] missing block undefined
[11:33:10.474] [API-->>请求] from:slug-props-article/example-1 id:234a0ee1-9890-43c6-a040-4060d390b2fb 
[11:33:12.026] [API<<--响应] 耗时:1200ms - from:slug-props-article/example-1
[11:33:12.028] 
[11:33:12.028] Error occurred prerendering page "/zh/article/example-1". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:12.028] 
[11:33:12.028] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:12.035] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:12.035]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:12.035]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:12.035]     at Array.every (<anonymous>)
[11:33:12.035]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:12.035]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:12.036]     at Array.every (<anonymous>)
[11:33:12.036]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:12.036]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:12.036]     at Array.every (<anonymous>)
[11:33:12.036]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:12.086] [API-->>请求] from:slug-props-article/example-2 id:6a37d9b2-e1c7-46e1-8933-1e69489ff3e3 
[11:33:12.255] [API<<--响应] 耗时:179ms - from:slug-props-article/example-2
[11:33:12.256] 
[11:33:12.256] Error occurred prerendering page "/zh/article/example-2". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:12.256] 
[11:33:12.257] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:12.257] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:12.257]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:12.257]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:12.257]     at Array.every (<anonymous>)
[11:33:12.257]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:12.257]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:12.258]     at Array.every (<anonymous>)
[11:33:12.258]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:12.258]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:12.258]     at Array.every (<anonymous>)
[11:33:12.258]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:12.320] [API-->>请求] from:slug-props-article/example-3 id:f2ed4d2e-abbd-42f0-9788-3f609b9d7637 
[11:33:13.426] [API<<--响应] 耗时:1052ms - from:slug-props-article/example-3
[11:33:13.427] 
[11:33:13.427] Error occurred prerendering page "/zh/article/example-3". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:13.427] 
[11:33:13.427] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:13.427] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:13.427]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:13.427]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:13.427]     at Array.every (<anonymous>)
[11:33:13.427]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:13.427]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:13.427]     at Array.every (<anonymous>)
[11:33:13.427]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:13.428]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:13.428]     at Array.every (<anonymous>)
[11:33:13.428]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:13.500] [API-->>请求] from:slug-props-article/example-4 id:0dfa64e4-e051-4a57-9826-4c96968d5cb2 
[11:33:14.433] [API<<--响应] 耗时:926ms - from:slug-props-article/example-4
[11:33:14.435] 
[11:33:14.435] Error occurred prerendering page "/zh/article/example-4". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:14.440] 
[11:33:14.441] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:14.441] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:14.441]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:14.441]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:14.442]     at Array.every (<anonymous>)
[11:33:14.442]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:14.442]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:14.442]     at Array.every (<anonymous>)
[11:33:14.442]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:14.443]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:14.443]     at Array.every (<anonymous>)
[11:33:14.443]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:14.535] [API-->>请求] from:slug-props-article/example-5 id:3d0d0e6f-3983-4aee-ac88-b4fd55612696 
[11:33:14.888] [API<<--响应] 耗时:381ms - from:slug-props-article/example-5
[11:33:14.889] 
[11:33:14.889] Error occurred prerendering page "/zh/article/example-5". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:14.889] 
[11:33:14.889] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:14.889] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:14.890]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:14.890]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:14.890]     at Array.every (<anonymous>)
[11:33:14.890]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:14.890]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:14.890]     at Array.every (<anonymous>)
[11:33:14.890]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:14.890]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:14.890]     at Array.every (<anonymous>)
[11:33:14.890]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:14.945] [API-->>请求] from:slug-props-article/guide id:205632d7-3fca-47ed-b3bf-97408797c6f4 
[11:33:15.096] [API<<--响应] 耗时:158ms - from:slug-props-article/guide
[11:33:15.097] 
[11:33:15.097] Error occurred prerendering page "/zh/article/guide". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:15.097] 
[11:33:15.097] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:15.097] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:15.097]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:15.097]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.097]     at Array.every (<anonymous>)
[11:33:15.098]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.098]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:15.098]     at Array.every (<anonymous>)
[11:33:15.098]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:15.098]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.098]     at Array.every (<anonymous>)
[11:33:15.098]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.160] [API-->>请求] from:slug-props-article/example-6 id:e4cbf392-1987-49e1-a189-413dec136f27 
[11:33:15.474] [API<<--响应] 耗时:157ms - from:slug-props-article/example-6
[11:33:15.478] 
[11:33:15.479] Error occurred prerendering page "/zh/article/example-6". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:15.479] 
[11:33:15.479] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:15.480] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:15.480]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:15.480]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.480]     at Array.every (<anonymous>)
[11:33:15.480]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.480]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:15.480]     at Array.every (<anonymous>)
[11:33:15.481]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:15.481]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.481]     at Array.every (<anonymous>)
[11:33:15.481]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.519] [API-->>请求] from:slug-props-article/example-7 id:0c426960-70ee-41ab-831e-7ba832359523 
[11:33:15.712] [API<<--响应] 耗时:162ms - from:slug-props-article/example-7
[11:33:15.712] 
[11:33:15.713] Error occurred prerendering page "/zh/article/example-7". Read more: https://nextjs.org/docs/messages/prerender-error
[11:33:15.713] 
[11:33:15.713] Error: Error serializing `.customNav[0].name` returned from `getStaticProps` in "/[prefix]/[slug]".
[11:33:15.713] Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
[11:33:15.713]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:446)
[11:33:15.713]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.713]     at Array.every (<anonymous>)
[11:33:15.713]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.714]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:820
[11:33:15.714]     at Array.every (<anonymous>)
[11:33:15.714]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:807)
[11:33:15.714]     at /vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:683
[11:33:15.714]     at Array.every (<anonymous>)
[11:33:15.714]     at r (/vercel/path0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:580)
[11:33:15.756] [API-->>请求] from:slug-props-article/example-8 id:d6e57918-6aa7-414b-902d-fe00c21a3aaf 
[11:33:16.010] [API<<--响应] 耗时:197ms - from:slug-props-article/example-8
[11:33:16.013]    Generating static pages (19/79) 
[11:33:16.019] 
[11:33:16.020] Error occurred prerendering page "/zh/article/example-8". Read more: https://nextjs.org/docs/messages/prerender-error

**相应配置**
相关的配置，例如notion_page_id；你的网站地址

**截图**
目前用老的deploy，想冲洗部署下
相关的页面，应该用结果

**环境**

- 操作系统:   macOS 
- 浏览器  chrome 
- 版本 应该是最新版

**Comment by tangly1024** [comment]
似乎是修改blog.config.js出现了格式错误，需要重新拉一下代码，或者还原一下blog.config.js即可。
