### ISSUE TITLE
点进博文正文后无法显示，随后404

### ISSUE THREAD

**Issue by undefined-Chen** [tangly1024/NotionNext#2816]
**描述bug**
我的博客配置了中文和英文页面，中文页面下的文章可以正常访问，但英语页面下在主页点击文章后无法正常显示文章内容，随后显示404。Vercel的Logs中有如下报错：
```
无法写入文件 Error: EROFS: read-only file system, open 'sitemap.xml'
    at Object.writeFileSync (node:fs:2368:20)
    at n (/var/task/.next/server/pages/index.js:25:16)
    at g (/var/task/.next/server/pages/index.js:25:894)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e3 (/var/task/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3907)
    at async es (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:26114)
    at async en.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026)
    at async /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:14817
    at async /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:13410 {
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: 'sitemap.xml'
}
```

**期望的正常结果**
正常显示文章内容。

**复现步骤**
正常配置，随后发布文章。

**环境**

- 【必填】NotionNext版本 4.7.4
- 【必填】主题 next
- 【必填】部署方案 vercel
- 【可选】操作系统: Windows
- 【可选】浏览器 Edge

**Comment by undefined-Chen** [comment]
我发现把slug前面的斜杠删掉就好了，前面没有注意到，打扰了......
