### ISSUE TITLE
Error: Cannot find module './STARTER'=希望升級到4.7.7但站點部署失敗

### ISSUE THREAD

**Issue by kid1980** [tangly1024/NotionNext#2924]
**描述遇到的问题**
重新佈署時一直失敗，相關錯誤日誌如下,有先使用NOTION AI幫忙找答案,說是STARTER這個模組找不到
[20:14:12.278] Running build in Washington, D.C., USA (East) – iad1
[20:14:12.367] Cloning github.com/kid1980/NotionNext (Branch: expext, Commit: ea8924b)
[20:14:12.375] Skipping build cache, deployment was triggered without cache.
[20:14:13.418] Cloning completed: 1.050s
[20:14:13.778] Running "vercel build"
[20:14:15.345] Vercel CLI 37.14.0
[20:14:15.800] Installing dependencies...
[20:14:16.104] yarn install v1.22.19
[20:14:16.175] [1/4] Resolving packages...
[20:14:16.725] [2/4] Fetching packages...
[20:14:45.100] [3/4] Linking dependencies...
[20:14:45.103] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[20:14:45.104] warning "react-notion-x > react-image@4.1.0" has unmet peer dependency "@babel/runtime@>=7".
[20:14:45.104] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[20:14:45.104] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[20:14:45.105] warning "react-notion-x > react-lazy-images > react-intersection-observer@6.4.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
[20:14:45.105] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[20:14:45.105] warning " > @typescript-eslint/eslint-plugin@7.16.0" has incorrect peer dependency "eslint@^8.56.0".
[20:14:45.106] warning "@typescript-eslint/eslint-plugin > @typescript-eslint/type-utils@7.16.0" has incorrect peer dependency "eslint@^8.56.0".
[20:14:45.106] warning "@typescript-eslint/eslint-plugin > @typescript-eslint/utils@7.16.0" has incorrect peer dependency "eslint@^8.56.0".
[20:14:45.106] warning " > @typescript-eslint/parser@7.16.0" has incorrect peer dependency "eslint@^8.56.0".
[20:14:45.107] warning " > eslint-config-next@13.5.6" has incorrect peer dependency "eslint@^7.23.0 || ^8.0.0".
[20:14:45.107] warning "eslint-config-next > @typescript-eslint/parser@6.20.0" has incorrect peer dependency "eslint@^7.0.0 || ^8.0.0".
[20:14:45.107] warning " > eslint-plugin-import@2.29.1" has incorrect peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
[20:14:45.107] warning "eslint-config-next > eslint-plugin-jsx-a11y@6.8.0" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
[20:14:45.107] warning "eslint-config-next > eslint-plugin-react@7.33.2" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
[20:14:45.108] warning "eslint-config-next > eslint-plugin-react-hooks@4.6.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
[20:14:45.108] warning " > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint@^7.12.1".
[20:14:45.108] warning " > eslint-plugin-promise@5.2.0" has incorrect peer dependency "eslint@^7.0.0".
[20:14:45.109] warning " > eslint-plugin-react@7.34.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
[20:14:45.109] warning " > eslint-plugin-react-hooks@4.6.2" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
[20:14:56.020] [4/4] Building fresh packages...
[20:14:56.223] success Saved lockfile.
[20:14:56.229] Done in 40.13s.
[20:14:56.262] Detected Next.js version: 14.2.4
[20:14:56.265] Running "yarn run build"
[20:14:56.461] yarn run v1.22.19
[20:14:56.503] $ next build
[20:14:58.004] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[20:14:58.009] This information is used to shape Next.js' roadmap and prioritize features.
[20:14:58.009] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[20:14:58.009] https://nextjs.org/telemetry
[20:14:58.009] 
[20:14:58.069]   ▲ Next.js 14.2.4
[20:14:58.069]   - Environments: .env.local
[20:14:58.069]   - Experiments (use with caution):
[20:14:58.069]     · scrollRestoration
[20:14:58.069] 
[20:14:58.069]    Skipping linting
[20:14:58.070]    Checking validity of types ...
[20:15:16.374]    Creating an optimized production build ...
[20:15:16.840] [默认主题] /vercel/path0/themes/simple
[20:15:30.851] Browserslist: caniuse-lite is outdated. Please run:
[20:15:30.851]   npx update-browserslist-db@latest
[20:15:30.851]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[20:15:46.518]  ✓ Compiled successfully
[20:15:46.519]    Collecting page data ...
[20:15:47.172] [Fetching Data] ea1c80e77b624989b0aba8312ffb01d6 category-paths
[20:15:47.178] [API-->>请求] from:category-paths id:ea1c80e77b624989b0aba8312ffb01d6 
[20:15:47.178] [Fetching Data] ea1c80e77b624989b0aba8312ffb01d6 category-paths
[20:15:47.178] [API-->>请求] from:category-paths id:ea1c80e77b624989b0aba8312ffb01d6 
[20:15:47.897] [Fetching Data] ea1c80e77b624989b0aba8312ffb01d6 page-paths
[20:15:47.899] [API-->>请求] from:page-paths id:ea1c80e77b624989b0aba8312ffb01d6 
[20:15:48.698] [API<<--响应] 耗时:780ms - from:category-paths
[20:15:48.721] [API-->>请求] from:config-table id:73b0e726-3ec5-4666-b65e-79e58cd5af26 
[20:15:49.049] [API<<--响应] 耗时:329ms - from:config-table
[20:15:49.052] [API-->>请求] from:data-notice id:919034f8-cdc3-40d0-99fb-a59f508bba21 
[20:15:49.187] [API<<--响应] 耗时:135ms - from:data-notice
[20:15:49.210] [API<<--缓存] from:tag-static-path root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:49.219] [API<<--缓存] from:tag-page-static-path root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:49.258] [API<<--响应] 耗时:1339ms - from:category-paths
[20:15:49.279] [API-->>请求] from:config-table id:73b0e726-3ec5-4666-b65e-79e58cd5af26 
[20:15:49.675] [API<<--响应] 耗时:396ms - from:config-table
[20:15:49.678] [API-->>请求] from:data-notice id:919034f8-cdc3-40d0-99fb-a59f508bba21 
[20:15:49.824] [API<<--响应] 耗时:146ms - from:data-notice
[20:15:50.320] [API<<--响应] 耗时:2393ms - from:page-paths
[20:15:50.340] [API-->>请求] from:config-table id:73b0e726-3ec5-4666-b65e-79e58cd5af26 
[20:15:50.649] [API<<--响应] 耗时:309ms - from:config-table
[20:15:50.652] [API-->>请求] from:data-notice id:919034f8-cdc3-40d0-99fb-a59f508bba21 
[20:15:51.078] [API<<--响应] 耗时:425ms - from:data-notice
[20:15:54.376]    Generating static pages (0/38) ...
[20:15:54.609] missing block undefined
[20:15:54.610] missing block undefined
[20:15:54.610] missing block undefined
[20:15:54.859]    Generating static pages (9/38) 
[20:15:54.994] [API<<--缓存] from:search-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:54.995] [API<<--缓存] from:search-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.027] [API<<--缓存] from:SignIn root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.068] 
[20:15:55.068] Error occurred prerendering page "/zh/sign-in/factor-one". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.068] 
[20:15:55.068] Error: Cannot find module './STARTER'
[20:15:55.068]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.069] 
[20:15:55.070] Error occurred prerendering page "/zh/sign-up". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.070] 
[20:15:55.071] Error: Cannot find module './STARTER'
[20:15:55.071]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.109] 
[20:15:55.109] Error occurred prerendering page "/zh/sign-up/sign-up". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.109] 
[20:15:55.109] Error: Cannot find module './STARTER'
[20:15:55.109]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.174] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.174] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.175]    Generating static pages (18/38) 
[20:15:55.212] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.257] 
[20:15:55.257] Error occurred prerendering page "/zh/tag/新闻". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.257] 
[20:15:55.257] Error: Cannot find module './STARTER'
[20:15:55.257]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.258] 
[20:15:55.258] Error occurred prerendering page "/zh/tag/工具". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.258] 
[20:15:55.258] Error: Cannot find module './STARTER'
[20:15:55.258]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.304] 
[20:15:55.304] Error occurred prerendering page "/zh/tag/开发". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.304] 
[20:15:55.304] Error: Cannot find module './STARTER'
[20:15:55.304]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.357] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.357] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.395] [API<<--缓存] from:tag-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.436] 
[20:15:55.436] Error occurred prerendering page "/zh/category/技术分享". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.436] 
[20:15:55.436] Error: Cannot find module './STARTER'
[20:15:55.437]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.437] 
[20:15:55.437] Error occurred prerendering page "/zh/category/知行合一". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.437] 
[20:15:55.437] Error: Cannot find module './STARTER'
[20:15:55.437]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.478] 
[20:15:55.478] Error occurred prerendering page "/zh/category/心情随笔". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.478] 
[20:15:55.478] Error: Cannot find module './STARTER'
[20:15:55.478]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.479]    Generating static pages (28/38) 
[20:15:55.523] [API<<--缓存] from:page-2 root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.561] [API<<--缓存] from:archive-index root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.610] 
[20:15:55.611] Error occurred prerendering page "/zh/404". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.611] 
[20:15:55.611] Error: Cannot find module './STARTER'
[20:15:55.611]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.611] [API<<--缓存] from:auth root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.682] 
[20:15:55.682] Error occurred prerendering page "/zh/category". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.682] 
[20:15:55.682] Error: Cannot find module './STARTER'
[20:15:55.682]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.731] 
[20:15:55.731] Error occurred prerendering page "/zh/search". Read more: https://nextjs.org/docs/messages/prerender-error
[20:15:55.732] 
[20:15:55.732] Error: Cannot find module './STARTER'
[20:15:55.732]     at /vercel/path0/.next/server/chunks/43414.js:77:114317
[20:15:55.732] [API<<--缓存] from:index root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.732] [RSS订阅] 生成/rss/feed.xml
[20:15:55.732] [API-->>请求] from:rss-content id:11830451-3d05-80aa-bf59-dcaa200f6019 
[20:15:55.773] [API<<--缓存] from:tag-index-props root-page-id:ea1c80e77b624989b0aba8312ffb01d6
[20:15:55.818]  ✓ Generating static pages (38/38)
[20:15:55.820] [API<<--响应] 耗时:146ms - from:rss-content
[20:15:55.820] [API-->>请求] from:rss-content id:919488b6-0f3c-4f4a-ad66-186644fcc8a1 
[20:15:55.929] 
[20:15:55.930] > Export encountered errors on following paths:
[20:15:55.930] 	/404: /zh/404
[20:15:55.930] 	/category/[category]: /zh/category/心情随笔
[20:15:55.930] 	/category/[category]: /zh/category/技术分享
[20:15:55.930] 	/category/[category]: /zh/category/知行合一
[20:15:55.930] 	/category: /zh/category
[20:15:55.931] 	/search: /zh/search
[20:15:55.931] 	/sign-in/[[...index]]: /zh/sign-in/factor-one
[20:15:55.931] 	/sign-up/[[...index]]: /zh/sign-up
[20:15:55.931] 	/sign-up/[[...index]]: /zh/sign-up/sign-up
[20:15:55.931] 	/tag/[tag]: /zh/tag/工具
[20:15:55.931] 	/tag/[tag]: /zh/tag/开发
[20:15:55.932] 	/tag/[tag]: /zh/tag/新闻
[20:15:56.010] error Command failed with exit code 1.
[20:15:56.011] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[20:15:56.029] Error: Command "yarn run build" exited with 1
[20:15:58.690] 

你的网站地址 
https://3592-git-expext-kids-projects-2217312f.vercel.app/

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: windows]
- 浏览器 EDGE

**Comment by zsr-lukezhang** [comment]
![image](https://github.com/user-attachments/assets/b46f6a92-11c9-43ec-8855-2454e665e9a9)
请开放站点。
不要发Dev站点，用Production。不然公众看不到。

**Comment by tangly1024** [comment]
>  Error: Cannot find module './STARTER'


在查找主题名为 STARTER的文件夹时发生错误。


解决方法； 在您的环境变量或者NOTION_CONFIG中将主题设置为 starter 而非STARTER 即可

**Comment by tangly1024** [comment]
该 issue 已超过一年没有进一步更新，所涉及的版本、部署环境或第三方服务状态可能已经变化，按过期关闭。若问题仍可在当前最新版本复现，请提交新的 issue，并附上复现步骤、NotionNext 版本、部署平台和相关日志。
