### ISSUE TITLE
Fork项目vercel部署时出错

### ISSUE THREAD

**Issue by DivaLotus** [tangly1024/NotionNext#293]
**问题**
简单说明你遇到的问题，相关的日志、错误信息
fork 了3.4版本，按照_**[博客教程](https://tangly1024.com/article/notion-next)**_填写好 NOTION_PAGE_ID 后，Deploy 失败

**Building**

[13:58:24.380] Cloning github.com/DivaLotus/Ming-s-project (Branch: main, Commit: 11623dc)
[13:58:24.802] Cloning completed: 422.437ms
[13:58:24.924] Installing build runtime...
[13:58:26.716] Build runtime installed: 1.791s
[13:58:27.544] No Build Cache available
[13:58:27.711] Installing dependencies...
[13:58:28.046] yarn install v1.22.17
[13:58:28.087] info No lockfile found.
[13:58:28.094] [1/4] Resolving packages...
[13:58:39.126] warning valine > leancloud-storage > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[13:58:39.144] warning valine > leancloud-storage > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[13:58:39.293] warning valine > leancloud-storage > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[13:58:39.459] warning valine > leancloud-storage > leancloud-realtime > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[13:58:40.382] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-node > @leancloud/adapters-superagent > superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[13:58:40.384] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-node > @leancloud/adapters-superagent > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[13:58:45.369] [2/4] Fetching packages...
[13:58:59.071] [3/4] Linking dependencies...
[13:58:59.072] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
[13:58:59.073] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
[13:58:59.074] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[13:58:59.074] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[13:58:59.075] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[13:58:59.075] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[13:58:59.075] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[13:58:59.076] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[13:58:59.079] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[13:58:59.118] warning Workspaces can only be enabled in private projects.
[13:59:09.625] [4/4] Building fresh packages...
[13:59:10.027] success Saved lockfile.
[13:59:10.033] Done in 41.99s.
[13:59:10.083] Detected Next.js version: 12.1.6
[13:59:10.085] Running "yarn run build"
[13:59:10.344] yarn run v1.22.17
[13:59:10.387] $ next build && next-sitemap --config next-sitemap.config.js
[13:59:10.934] info  - Loaded env from /vercel/path0/.env.local
[13:59:11.095] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[13:59:11.095] This information is used to shape Next.js' roadmap and prioritize features.
[13:59:11.095] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[13:59:11.095] https://nextjs.org/telemetry
[13:59:11.095] 
[13:59:11.134] info  - Checking validity of types...
[13:59:13.448] info  - Creating an optimized production build...
[13:59:55.628] info  - Compiled successfully
[13:59:55.628] info  - Collecting page data...
[13:59:56.483] TypeError: Cannot read properties of undefined (reading 'startsWith')
[13:59:56.483]     at connectionStringHasValidScheme (/vercel/path0/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
[13:59:56.483]     at new ConnectionString (/vercel/path0/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
[13:59:56.484]     at parseOptions (/vercel/path0/node_modules/mongodb/lib/connection_string.js:209:17)
[13:59:56.484]     at new MongoClient (/vercel/path0/node_modules/mongodb/lib/mongo_client.js:62:63)
[13:59:56.484]     at Function.connect (/vercel/path0/node_modules/mongodb/lib/mongo_client.js:195:33)
[13:59:56.484]     at Object.mongo_db_cache_getCache [as getCache] (/vercel/path0/.next/server/chunks/334.js:107:38)
[13:59:56.484]     at getDataFromCache (/vercel/path0/.next/server/chunks/334.js:196:27)
[13:59:56.485]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13:59:56.485]     at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:387:18)
[13:59:56.485]     at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:353:88)
[13:59:56.488] 
[13:59:56.488] > Build error occurred
[13:59:56.493] TypeError: Cannot read properties of undefined (reading 'db')
[13:59:56.494]     at Object.mongo_db_cache_getCache [as getCache] (/vercel/path0/.next/server/chunks/334.js:110:24)
[13:59:56.494]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13:59:56.494]     at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:387:18)
[13:59:56.494]     at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:353:88)
[13:59:56.495]     at async getStaticPaths (/vercel/path0/.next/server/pages/article/[slug].js:142:27)
[13:59:56.495]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
[13:59:56.495]     at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
[13:59:56.495]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[13:59:56.496]   type: 'TypeError'
[13:59:56.496] }
[13:59:56.582] error Command failed with exit code 1.
[13:59:56.582] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:59:56.593] Error: Command "yarn run build" exited with 1

**相应配置**
notion_page_id:2bd4567ee66a4dfeb63427ad36c31654
网址：https://ming-s-project-7u21ujpxy-divalotus.vercel.app/

**环境**

- 操作系统:：windows
- 浏览器 ：chrome
- 版本：3.4.0

**Comment by tangly1024** [comment]
- 感谢反馈，问题已修复，原因是代码BUG导致。

- 更新或重新fork后即可部署成功。

**Comment by DivaLotus** [comment]
感谢修复，重新部署后问题已解决
