### ISSUE TITLE
更新blog.config.js的加载文章预览时出错

### ISSUE THREAD

**Issue by zhuoxi-lab** [tangly1024/NotionNext#360]
**描述遇到的问题**
您好！我在Update blog.config.js时，看到里面有“是否在列表加载文章预览”，想作预览，就把false改成了true，deploy显示error，我就把false改成了true，结果依旧显示error

**相应配置**
相关的配置，例如notion_page_id；你的网站地址
id：88ef170b1ff145c685b895f8710a2d7e；网站地址：https://notion-next-beige-delta.vercel.app/

**截图**
相关的页面，应该用结果
截图我不知道怎么上传图片orz，就复制了一下显示错误的：
预呈现页面“/links”时发生错误。阅读更多：https://nextjs.org/docs/messages/prerender-error
TypeError：无法读取未定义的属性（读取“地图”）
    在 ys (/vercel/path0/.next/server/chunks/635.js:24:105247)
    在 d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    在 bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    在 abrender (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    在国外（/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83）
    在 Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    在 Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:804:45)
    在 Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:391:51)
    在 Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:202:20)
    在 Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
后面还有一段：
发生构建错误
错误：导出在以下路径上遇到错误：
	/[蛞蝓]：/链接
    在 /vercel/path0/node_modules/next/dist/export/index.js:398:19
    在 runMicrotasks (<匿名>)
    在 processTicksAndRejections (节点:internal/process/task_queues:96:5)
    在异步 Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
    在异步 /vercel/path0/node_modules/next/dist/build/index.js:1034:21
    在异步 Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
    在异步 /vercel/path0/node_modules/next/dist/build/index.js:910:17
    在异步 Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
    在异步 Object.build [默认] (/vercel/path0/node_modules/next/dist/build/index.js:58:29)
错误命令失败，退出代码为 1。

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]windows
- 浏览器 [例如. chrome, safari, firefox]Chrome
- 版本 [e.g. 22]e.g.99.0.4844.82
- 大概就是这样！

**Comment by zhuoxi-lab** [comment]
补充一下之后设置了很多词，包括直接fork过来只改基本信息，但还是同样的问题：
[10:46:39.774] Cloning github.com/zhuoxi-lab/NotionNext (Branch: main, Commit: b36c8f6)
[10:46:40.162] Cloning completed: 387.389ms
[10:46:40.946] Looking up build cache...
[10:46:41.176] Build Cache not found
[10:46:41.400] Running "vercel build"
[10:46:41.902] Vercel CLI 28.1.2
[10:46:42.215] Installing dependencies...
[10:46:42.562] yarn install v1.22.17
[10:46:42.603] info No lockfile found.
[10:46:42.610] [1/4] Resolving packages...
[10:46:57.267] warning valine > leancloud-storage > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[10:46:57.329] warning valine > leancloud-storage > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[10:46:57.330] warning valine > leancloud-storage > leancloud-realtime > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[10:46:57.387] warning valine > leancloud-storage > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[10:46:57.982] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[10:46:57.988] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[10:47:04.593] [2/4] Fetching packages...
[10:47:21.014] [3/4] Linking dependencies...
[10:47:21.017] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
[10:47:21.017] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
[10:47:21.018] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[10:47:21.018] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[10:47:21.018] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[10:47:21.018] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[10:47:21.019] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[10:47:21.019] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[10:47:21.023] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[10:47:31.805] [4/4] Building fresh packages...
[10:47:32.246] success Saved lockfile.
[10:47:32.252] Done in 49.69s.
[10:47:32.290] Detected Next.js version: 12.1.6
[10:47:32.291] Running "yarn run build"
[10:47:32.563] yarn run v1.22.17
[10:47:32.607] $ next build && next-sitemap --config next-sitemap.config.js
[10:47:33.108] info  - Loaded env from /vercel/path0/.env.local
[10:47:33.341] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[10:47:33.341] This information is used to shape Next.js' roadmap and prioritize features.
[10:47:33.341] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[10:47:33.342] https://nextjs.org/telemetry
[10:47:33.342] 
[10:47:33.381] info  - Checking validity of types...
[10:47:35.831] info  - Creating an optimized production build...
[10:48:22.882] info  - Compiled successfully
[10:48:22.883] info  - Collecting page data...
[10:48:23.857] [请求API] from:slug-paths id:88ef170b1ff145c685b895f8710a2d7e 
[10:48:23.925] [请求API] from:slug-paths id:88ef170b1ff145c685b895f8710a2d7e 
[10:48:23.949] [请求API] from:category-paths id:88ef170b1ff145c685b895f8710a2d7e 
[10:48:24.313] [响应成功]: from:slug-paths id:88ef170b1ff145c685b895f8710a2d7e
[10:48:24.313] [API耗时] 456ms
[10:48:24.317] PageIds: 从collectionQuery获取 {
[10:48:24.317]   '0a5043bd-68ef-495f-988f-28af126aa0c1': {
[10:48:24.317]     '66df6a85-482a-4503-9667-8a1be3be0018': { collection_group_results: [Object] }
[10:48:24.317]   }
[10:48:24.317] }
[10:48:24.356] [命中缓存]: from:page-paths root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:24.367] [命中缓存]: from:tag-static-path root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:24.413] [响应成功]: from:slug-paths id:88ef170b1ff145c685b895f8710a2d7e
[10:48:24.414] [API耗时] 489ms
[10:48:24.418] PageIds: 从collectionQuery获取 {
[10:48:24.418]   '0a5043bd-68ef-495f-988f-28af126aa0c1': {
[10:48:24.418]     '66df6a85-482a-4503-9667-8a1be3be0018': { collection_group_results: [Object] }
[10:48:24.418]   }
[10:48:24.418] }
[10:48:24.455] [响应成功]: from:category-paths id:88ef170b1ff145c685b895f8710a2d7e
[10:48:24.456] [API耗时] 507ms
[10:48:24.460] PageIds: 从collectionQuery获取 {
[10:48:24.460]   '0a5043bd-68ef-495f-988f-28af126aa0c1': {
[10:48:24.460]     '66df6a85-482a-4503-9667-8a1be3be0018': { collection_group_results: [Object] }
[10:48:24.460]   }
[10:48:24.460] }
[10:48:25.755] info  - Generating static pages (0/31)
[10:48:25.913] [命中缓存]: from:404 root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:25.957] [命中缓存]: from:category-index-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:25.961] [命中缓存]: from:archive-index root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:25.978] [命中缓存]: from:index root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.001] [命中缓存]: from:search-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.029] info  - Generating static pages (7/31)
[10:48:26.035] [命中缓存]: from:tag-index-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.041] [命中缓存]: from:slug-props-message root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.043] [请求API] from:slug id:7e386848-1321-4eff-a91b-45b0a0b3f8dc 
[10:48:26.054] [命中缓存]: from:slug-props-links root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.056] [请求API] from:slug id:2568f9eb-b896-4f46-9a2e-704a977bcaf1 
[10:48:26.060] [命中缓存]: from:slug-props-https://github.com/tangly1024/NotionNext root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.061] [请求API] from:slug id:8a065e17-97a6-4653-9415-9ca536957bd7 
[10:48:26.203] [响应成功]: from:slug id:8a065e17-97a6-4653-9415-9ca536957bd7
[10:48:26.204] [API耗时] 142ms
[10:48:26.233] [命中缓存]: from:slug-props-example-3 root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.234] [请求API] from:slug id:3bfb0d13-980b-4325-b9a8-f8ab74967c61 
[10:48:26.369] [响应成功]: from:slug id:2568f9eb-b896-4f46-9a2e-704a977bcaf1
[10:48:26.369] [API耗时] 313ms
[10:48:26.390] "alias" missing block bc33df69-a5d2-4ec3-a8d2-0e99f3ef0f1b
[10:48:26.393] 
[10:48:26.393] Error occurred prerendering page "/links". Read more: https://nextjs.org/docs/messages/prerender-error
[10:48:26.393] TypeError: Cannot read properties of undefined (reading 'map')
[10:48:26.393]     at ys (/vercel/path0/.next/server/chunks/635.js:24:105247)
[10:48:26.393]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[10:48:26.393]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[10:48:26.393]     at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[10:48:26.393]     at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[10:48:26.393]     at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[10:48:26.393]     at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:804:45)
[10:48:26.393]     at Object.defaultGetInitialProps (/vercel/path0/node_modules/next/dist/server/render.js:391:51)
[10:48:26.393]     at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:202:20)
[10:48:26.394]     at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:153:61)
[10:48:26.394] [命中缓存]: from:search-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.396] 全文搜索缓存 page_block_d5154b91-220d-41e2-baa4-846f7ab2c5ae false
[10:48:26.396] 全文搜索缓存 page_block_c06ed535-1f3c-4c55-8c6e-32a44fb5b93e false
[10:48:26.396] 全文搜索缓存 page_block_0271de98-05fd-400f-abf1-4dfd437a7fc5 false
[10:48:26.396] 全文搜索缓存 page_block_86a2e9fd-5ac4-4523-8ed5-6e1bcc4cdc97 false
[10:48:26.396] 全文搜索缓存 page_block_b2f53ffb-ea63-4703-a26b-bbdd01c89983 false
[10:48:26.410] info  - Generating static pages (15/31)
[10:48:26.411] [命中缓存]: from:tag-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.427] [命中缓存]: from:tag-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.431] [响应成功]: from:slug id:7e386848-1321-4eff-a91b-45b0a0b3f8dc
[10:48:26.431] [API耗时] 387ms
[10:48:26.451] [命中缓存]: from:tag-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.471] [命中缓存]: from:tag-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.484] [命中缓存]: from:slug-props-text root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.486] [响应成功]: from:slug id:3bfb0d13-980b-4325-b9a8-f8ab74967c61
[10:48:26.486] [API耗时] 251ms
[10:48:26.486] [请求API] from:slug id:d5154b91-220d-41e2-baa4-846f7ab2c5ae 
[10:48:26.493] [命中缓存]: from:slug-props-c06ed535-1f3c-4c55-8c6e-32a44fb5b93e root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.494] [请求API] from:slug id:c06ed535-1f3c-4c55-8c6e-32a44fb5b93e 
[10:48:26.520] [命中缓存]: from:slug-props-0271de98-05fd-400f-abf1-4dfd437a7fc5 root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.521] [请求API] from:slug id:0271de98-05fd-400f-abf1-4dfd437a7fc5 
[10:48:26.631] [响应成功]: from:slug id:d5154b91-220d-41e2-baa4-846f7ab2c5ae
[10:48:26.631] [API耗时] 144ms
[10:48:26.662] [命中缓存]: from:slug-props-86a2e9fd-5ac4-4523-8ed5-6e1bcc4cdc97 root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.663] [请求API] from:slug id:86a2e9fd-5ac4-4523-8ed5-6e1bcc4cdc97 
[10:48:26.804] [响应成功]: from:slug id:c06ed535-1f3c-4c55-8c6e-32a44fb5b93e
[10:48:26.804] [API耗时] 309ms
[10:48:26.836] info  - Generating static pages (23/31)
[10:48:26.838] [命中缓存]: from:slug-props-b2f53ffb-ea63-4703-a26b-bbdd01c89983 root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:26.839] [请求API] from:slug id:b2f53ffb-ea63-4703-a26b-bbdd01c89983 
[10:48:26.943] [响应成功]: from:slug id:0271de98-05fd-400f-abf1-4dfd437a7fc5
[10:48:26.943] [API耗时] 422ms
[10:48:26.998] [命中缓存]: from:category-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:27.011] [命中缓存]: from:category-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:27.020] [命中缓存]: from:category-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:27.032] [命中缓存]: from:category-props root-page-id:88ef170b1ff145c685b895f8710a2d7e
[10:48:27.141] [响应成功]: from:slug id:86a2e9fd-5ac4-4523-8ed5-6e1bcc4cdc97
[10:48:27.141] [API耗时] 478ms
[10:48:27.169] [响应成功]: from:slug id:b2f53ffb-ea63-4703-a26b-bbdd01c89983
[10:48:27.169] [API耗时] 330ms
[10:48:27.202] info  - Generating static pages (31/31)
[10:48:27.205] 
[10:48:27.205] > Build error occurred
[10:48:27.208] Error: Export encountered errors on following paths:
[10:48:27.208] 	/[slug]: /links
[10:48:27.208]     at /vercel/path0/node_modules/next/dist/export/index.js:398:19
[10:48:27.209]     at runMicrotasks (<anonymous>)
[10:48:27.209]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10:48:27.209]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[10:48:27.209]     at async /vercel/path0/node_modules/next/dist/build/index.js:1034:21
[10:48:27.209]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[10:48:27.216]     at async /vercel/path0/node_modules/next/dist/build/index.js:910:17
[10:48:27.216]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[10:48:27.217]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:58:29)
[10:48:27.279] error Command failed with exit code 1.
[10:48:27.279] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:48:27.289] Error! Command "yarn run build" exited with 1

**Comment by zhuoxi-lab** [comment]
再次补充。发现是notion那边的问题，slug有重复而且有没有填的。问题已经解决了。
但是还是有一个问题就是发现我的友链不更新了，notion这边添加或者删改，在博客界面都不会更新。

**Comment by tangly1024** [comment]
Hello，
根据日志确定：问题出在你的links(友链)页面无法正常解析，导致博客无法 正常更新或编译。
似乎是此页面的数据格式异常，后续将尝试修复此兼容问题。

彻底修复这个BUG有点棘手，因为我需要和你完全一样的步骤来创建这个友链表格，我的建议是可以重新创建一个友链页面，将现有的链页面移出博客列表。

可以参考 复制此友链页面：

https://tanghh.notion.site/b9e5afa7db274aea95fb3fd5fcf81846

预览效果
https://preview.tangly1024.com/links
