### ISSUE TITLE
R

### ISSUE THREAD

**Issue by wyih** [tangly1024/NotionNext#362]
**描述bug**
简单说明bug的现象、相关的错误提示、日志等

**复现步骤**
出现这个bug的操作步骤

**期望的正常结果**
希望按这个步骤，正常操作结果是什么

**截图**
相关的页面，应该用结果

**环境**

- 操作系统: [例如. iOS, Android, macOS, windows]
- 浏览器 [例如. chrome, safari, firefox]
- 版本 [e.g. 22]

**补充说明**
与问题相关的其它说明

**Comment by tangly1024** [comment]
嗨，项目中默认没有开启R语言的支持，

如果需要，开启的方式很简单：

## 修改一个文件
在[components/NotionPage.js](https://github.com/tangly1024/NotionNext/blob/feature/language-r/components/NotionPage.js#L11) 文件中加入以下代码即可
```
import 'prismjs/components/prism-r.js'

```

- 参考示例代码： https://github.com/tangly1024/NotionNext/commit/7d309319f023ca6be6fc2efb11dcb370c0735818


## 开启后R语言展示的效果如下：
<img width="813" alt="图片" src="https://user-images.githubusercontent.com/15920488/190938372-bdb68525-b6a8-43fb-a994-885eff28c3c7.png">

**Comment by wyih** [comment]
我按这个改了之后没有成功，错误代码如下：
Build Failed
Command "yarn run build" exited with 1

https://github.com/wyih/NotionNext/commit/257caebab62c920f38c4008190bc371080f06583

**Comment by tangly1024** [comment]
可能是代码版本老旧导致的问题，请将更新到最新版后，再尝试修改该文件

**Comment by wyih** [comment]
我更新了之后仍然没有高亮 

https://blog.yhong.wang/article/sd_tg_bot 

已经Sync至最新

**Comment by wyih** [comment]
> 嗨，项目中默认没有开启R语言的支持，
> 
> 如果需要，开启的方式很简单：
> 
> ## 修改一个文件
> 在[components/NotionPage.js](https://github.com/tangly1024/NotionNext/blob/feature/language-r/components/NotionPage.js#L11) 文件中加入以下代码即可
> 
> ```
> import 'prismjs/components/prism-r.js'
> ```
> 
>  * 参考示例代码： [7d30931](https://github.com/tangly1024/NotionNext/commit/7d309319f023ca6be6fc2efb11dcb370c0735818)
> 
> ## 开启后R语言展示的效果如下：
> <img alt="图片" width="813" src="https://user-images.githubusercontent.com/15920488/190938372-bdb68525-b6a8-43fb-a994-885eff28c3c7.png">

我再改下这个试下

**Comment by wyih** [comment]
> 我按这个改了之后没有成功，错误代码如下： Build Failed Command "yarn run build" exited with 1
> 
> [wyih@257caeb](https://github.com/wyih/NotionNext/commit/257caebab62c920f38c4008190bc371080f06583)

和之间情况一样 Sync之后还是无法Redeploy导致无法生效

![Uploading 91C73746-601F-4C84-B553-AD1DF65EF5C5.png…]()

**Comment by wyih** [comment]
错误提示如下

> [19:23:12] Cloning github.com/wyih/NotionNext (Branch: main, Commit: 6036ec2)
[19:23:12] Cloning completed: 310.507ms
[19:23:13] Looking up build cache...
[19:23:13] Build Cache not found
[19:23:13] Running "vercel build"
[19:23:14] Vercel CLI 28.4.12-5b68066
[19:23:14] Installing dependencies...
[19:23:15] yarn install v1.22.17
[19:23:15] info No lockfile found.
[19:23:15] [1/4] Resolving packages...
[19:23:18] warning notion-client > got > @types/cacheable-request > @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
[19:23:22] warning valine > leancloud-storage > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[19:23:22] warning valine > leancloud-storage > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[19:23:22] warning valine > leancloud-storage > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[19:23:22] warning valine > leancloud-storage > leancloud-realtime > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[19:23:23] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-node > @leancloud/adapters-superagent > superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[19:23:23] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-node > @leancloud/adapters-superagent > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[19:23:26] [2/4] Fetching packages...
[19:23:48] [3/4] Linking dependencies...
[19:23:48] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
[19:23:48] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
[19:23:48] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[19:23:48] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[19:23:48] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[19:23:48] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[19:23:48] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[19:23:48] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[19:23:49] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[19:23:58] [4/4] Building fresh packages...
[19:23:59] success Saved lockfile.
[19:23:59] Done in 43.78s.
[19:23:59] Detected Next.js version: 12.1.6
[19:23:59] Running "yarn run build"
[19:23:59] yarn run v1.22.17
[19:23:59] $ next build && next-sitemap --config next-sitemap.config.js
[19:24:00] info  - Loaded env from /vercel/path0/.env.local
[19:24:00] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[19:24:00] This information is used to shape Next.js' roadmap and prioritize features.
[19:24:00] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[19:24:00] https://nextjs.org/telemetry
[19:24:00] 
[19:24:01] info  - Checking validity of types...
[19:24:04] info  - Creating an optimized production build...
[19:25:07] info  - Compiled successfully
[19:25:07] info  - Collecting page data...
[19:25:09] [请求API] from:slug-paths id:4015efcd15b84d7ea5c17f9d27b0ef8a 
[19:25:09] [请求API] from:category-paths id:4015efcd15b84d7ea5c17f9d27b0ef8a 
[19:25:09] [请求API] from:page-paths id:4015efcd15b84d7ea5c17f9d27b0ef8a 
[19:25:09] [响应成功]: from:category-paths
[19:25:09] [API耗时] 496ms
[19:25:09] [响应成功]: from:slug-paths
[19:25:09] [API耗时] 559ms
[19:25:09] 
[19:25:09] > Build error occurred
[19:25:09] TypeError: Cannot read properties of undefined (reading '0')
[19:25:09]     at getPageProperties (/vercel/path0/.next/server/chunks/334.js:742:38)
[19:25:09]     at getPageRecordMapByNotionAPI (/vercel/path0/.next/server/chunks/334.js:587:105)
[19:25:09]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[19:25:09]     at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:395:27)
[19:25:09]     at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:354:88)
[19:25:09]     at async getStaticPaths (/vercel/path0/.next/server/pages/category/[category].js:76:29)
[19:25:09]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
[19:25:09]     at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
[19:25:09]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[19:25:09]   type: 'TypeError'
[19:25:09] }
[19:25:10] error Command failed with exit code 1.
[19:25:10] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[19:25:10] Error: Command "yarn run build" exited with 1

**Comment by tangly1024** [comment]
> r: Cannot read properties of undefined

此部署问题由于代码漏洞导致，最新版本已经修复，相关的issue https://github.com/tangly1024/NotionNext/issues/415
