### ISSUE TITLE
在vercel部署失败

### ISSUE THREAD

**Issue by tsq456** [tangly1024/NotionNext#415]
部署失败啦，请求帮助！

具体提示如下：

[09:15:00.836] Cloning github.com/tsq456/NotionNext (Branch: main, Commit: 5c0aff0)
[09:15:01.289] Cloning completed: 452.787ms
[09:15:01.771] No Build Cache available
[09:15:01.810] Running "vercel build"
[09:15:02.305] Vercel CLI 28.4.12-05a80a4
[09:15:02.639] Installing dependencies...
[09:15:02.987] yarn install v1.22.17
[09:15:03.026] info No lockfile found.
[09:15:03.033] [1/4] Resolving packages...
[09:15:08.654] warning notion-client > got > @types/cacheable-request > @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
[09:15:14.215] warning valine > leancloud-storage > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[09:15:14.260] warning valine > leancloud-storage > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[09:15:14.285] warning valine > leancloud-storage > leancloud-realtime > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[09:15:14.308] warning valine > leancloud-storage > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[09:15:14.966] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
[09:15:14.968] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[09:15:21.080] [2/4] Fetching packages...
[09:15:37.260] [3/4] Linking dependencies...
[09:15:37.262] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
[09:15:37.263] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
[09:15:37.264] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "react@15.x || 16.x".
[09:15:37.265] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[09:15:37.265] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[09:15:37.265] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[09:15:37.265] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[09:15:37.266] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[09:15:37.269] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[09:15:48.759] [4/4] Building fresh packages...
[09:15:49.198] success Saved lockfile.
[09:15:49.203] Done in 46.22s.
[09:15:49.257] Detected Next.js version: 12.1.6
[09:15:49.259] Running "yarn run build"
[09:15:49.529] yarn run v1.22.17
[09:15:49.572] $ next build && next-sitemap --config next-sitemap.config.js
[09:15:50.053] info  - Loaded env from /vercel/path0/.env.local
[09:15:50.247] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[09:15:50.247] This information is used to shape Next.js' roadmap and prioritize features.
[09:15:50.247] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[09:15:50.248] https://nextjs.org/telemetry
[09:15:50.248] 
[09:15:50.287] info  - Checking validity of types...
[09:15:52.587] info  - Creating an optimized production build...
[09:16:39.187] info  - Compiled successfully
[09:16:39.188] info  - Collecting page data...
[09:16:40.296] [请求API] from:slug-paths id:87cc3c5c317a40c0bf0482bd66fe9a03 
[09:16:40.367] [请求API] from:category-paths id:87cc3c5c317a40c0bf0482bd66fe9a03 
[09:16:40.484] [请求API] from:page-paths id:87cc3c5c317a40c0bf0482bd66fe9a03 
[09:16:40.959] [响应成功]: from:category-paths
[09:16:40.959] [API耗时] 593ms
[09:16:40.960] [响应成功]: from:page-paths
[09:16:40.960] [API耗时] 476ms
[09:16:40.969] [响应成功]: from:slug-paths
[09:16:40.969] [API耗时] 674ms
[09:16:40.983] 
<font color="red">
[09:16:40.983] > Build error occurred
[09:16:40.990] TypeError: Cannot read properties of undefined (reading '0')
[09:16:40.990]     at getPageProperties (/vercel/path0/.next/server/chunks/334.js:743:42)
[09:16:40.990]     at getPageRecordMapByNotionAPI (/vercel/path0/.next/server/chunks/334.js:587:105)
[09:16:40.990]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[09:16:40.991]     at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:395:27)
[09:16:40.991]     at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:354:88)
[09:16:40.991]     at async getStaticPaths (/vercel/path0/.next/server/pages/page/[page].js:73:28)
[09:16:40.993]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
[09:16:40.993]     at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
[09:16:40.993]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[09:16:40.993]   type: 'TypeError'
[09:16:40.994] }
[09:16:41.052] error Command failed with exit code 1.
[09:16:41.052] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[09:16:41.071] Error: Command "yarn run build" exited with 1
</font>

**Comment by wyih** [comment]
我也有类似的错误：


> Build error occurred
--
10:03:01.560 | TypeError: Cannot read properties of undefined (reading '0')
10:03:01.560 | at getPageProperties (/vercel/path0/.next/server/chunks/334.js:742:38)
10:03:01.561 | at getPageRecordMapByNotionAPI (/vercel/path0/.next/server/chunks/334.js:587:105)
10:03:01.561 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
10:03:01.561 | at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:395:27)
10:03:01.561 | at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:354:88)
10:03:01.561 | at async getStaticPaths (/vercel/path0/.next/server/pages/[...slug].js:148:27)
10:03:01.561 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
10:03:01.561 | at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
10:03:01.561 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
10:03:01.562 | type: 'TypeError'
10:03:01.562 | }
10:03:01.624 | error Command failed with exit code 1.
10:03:01.624 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:03:01.649 | Error: Command "yarn run build" exited with 1

**Comment by tsq456** [comment]
> 我也有类似的错误：
> 
> > Build error occurred
> > --
> > 10:03:01.560 | TypeError: Cannot read properties of undefined (reading '0')
> > 10:03:01.560 | at getPageProperties (/vercel/path0/.next/server/chunks/334.js:742:38)
> > 10:03:01.561 | at getPageRecordMapByNotionAPI (/vercel/path0/.next/server/chunks/334.js:587:105)
> > 10:03:01.561 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 10:03:01.561 | at async getNotionPageData (/vercel/path0/.next/server/chunks/334.js:395:27)
> > 10:03:01.561 | at async getGlobalNotionData (/vercel/path0/.next/server/chunks/334.js:354:88)
> > 10:03:01.561 | at async getStaticPaths (/vercel/path0/.next/server/pages/[...slug].js:148:27)
> > 10:03:01.561 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
> > 10:03:01.561 | at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
> > 10:03:01.561 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
> > 10:03:01.562 | type: 'TypeError'
> > 10:03:01.562 | }
> > 10:03:01.624 | error Command failed with exit code 1.
> > 10:03:01.624 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > 10:03:01.649 | Error: Command "yarn run build" exited with 1

感觉像是Vercel那边的问题，具体也不懂，等作者回复吧。

**Comment by tangly1024** [comment]
感谢楼上几位老铁们的反馈🥰，已确认是代码的漏洞导致，已在[最新的提交中](https://github.com/tangly1024/NotionNext/pull/416)修复此问题，更新即可解决。

**Comment by tangly1024** [comment]
> 刚刚部署还是报错。
> 
> [17:43:29.423] Cloning github.com/mx4994/NotionNext (Branch: main, Commit: [03b0dfa](https://github.com/tangly1024/NotionNext/commit/03b0dfae7b86f5de1a57ac09df92255fc208339c)) [17:43:30.070] Cloning completed: 646.351ms [17:43:30.569] Looking up build cache... [17:43:30.810] Build Cache not found [17:43:30.860] Running "vercel build" [17:43:31.501] Vercel CLI 28.4.12-05a80a4 [17:43:31.933] Installing dependencies... [17:43:32.350] yarn install v1.22.17 [17:43:32.405] info No lockfile found. [17:43:32.416] [1/4] Resolving packages... [17:43:39.362] warning notion-client > got > @types/cacheable-request > @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed. [17:43:44.256] warning valine > leancloud-storage > uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. [17:43:44.314] warning valine > leancloud-storage > leancloud-realtime > uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. [17:43:44.353] warning valine > leancloud-storage > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent. We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing. See the releases tab for more information at https://github.com/visionmedia/superagent/releases. [17:43:44.610] warning valine > leancloud-storage > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau [17:43:45.100] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent@5.3.1: Please upgrade to v7.0.2+ of superagent. We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing. See the releases tab for more information at https://github.com/visionmedia/superagent/releases. [17:43:45.104] warning valine > leancloud-storage > leancloud-realtime > @leancloud/platform-adapters-browser > @leancloud/adapters-superagent > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau [17:43:48.678] [2/4] Fetching packages... [17:44:11.707] [3/4] Linking dependencies... [17:44:11.710] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "[react@0.13.x](mailto:react@0.13.x) || 0.14.x || 15.x.x". [17:44:11.710] warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "[react-dom@0.13.x](mailto:react-dom@0.13.x) || 0.14.x || 15.x.x". [17:44:11.711] warning "react-facebook > react-spinner-children@1.0.8" has incorrect peer dependency "[react@15.x](mailto:react@15.x) || 16.x". [17:44:11.712] warning " > react-messenger-customer-chat@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0". [17:44:11.713] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16". [17:44:11.713] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16". [17:44:11.713] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7". [17:44:11.714] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0". [17:44:11.719] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta". [17:44:21.382] [4/4] Building fresh packages... [17:44:22.033] success Saved lockfile. [17:44:22.041] Done in 49.70s. [17:44:22.099] Detected Next.js version: 12.1.6 [17:44:22.102] Running "yarn run build" [17:44:22.425] yarn run v1.22.17 [17:44:22.486] $ next build && next-sitemap --config next-sitemap.config.js [17:44:23.075] info - Loaded env from /vercel/path0/.env.local [17:44:23.607] Attention: Next.js now collects completely anonymous telemetry regarding usage. [17:44:23.610] This information is used to shape Next.js' roadmap and prioritize features. [17:44:23.610] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL: [17:44:23.610] https://nextjs.org/telemetry [17:44:23.610] [17:44:23.663] info - Checking validity of types... [17:44:26.751] info - Creating an optimized production build... [17:45:29.395] info - Compiled successfully [17:45:29.395] info - Collecting page data... [17:45:30.920] [请求API] from:slug-paths id:103dabfa15814c25b8ff77134d0ea955 [17:45:30.948] [请求API] from:category-paths id:103dabfa15814c25b8ff77134d0ea955 [17:45:31.016] [请求API] from:page-paths id:103dabfa15814c25b8ff77134d0ea955 [17:45:31.096] [响应成功]: from:slug-paths [17:45:31.096] [API耗时] 178ms [17:45:31.098] pageId "103dabfa-1581-4c25-b8ff-77134d0ea955" is not a database [17:45:31.101] [17:45:31.101] > Build error occurred [17:45:31.104] TypeError: Cannot read properties of undefined (reading 'map') [17:45:31.104] at getStaticPaths (/vercel/path0/.next/server/pages/[...slug].js:152:25) [17:45:31.104] at processTicksAndRejections (node:internal/process/task_queues:96:5) [17:45:31.104] at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31) [17:45:31.104] at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119 [17:45:31.105] at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) { [17:45:31.105] type: 'TypeError' [17:45:31.105] } [17:45:31.168] error Command failed with exit code 1. [17:45:31.168] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. [17:45:31.191] Error: Command "yarn run build" exited with 1

# 祖耀检查配置
请检查 notion-page-Id 是否有误

103dabfa-1581-4c25-b8ff-77134d0ea955
