### ISSUE TITLE
部署失败，生成 `/archive` 页面失败

### ISSUE THREAD

**Issue by Vaayne** [tangly1024/NotionNext#671]
**描述遇到的问题**

部署失败，准确的是说生成  `/archive`页面失败，API 获取 Notion 的数据是成功的，因为这个 Log 我也看不出来具体的原因，所以只好发 issue 请作者帮忙看看。

应该是和我的 Notion Page 有关，因为我使用测试的 Page 是可以成功的。烦请帮忙看一下原因，多谢。
```
...
21:08:06.750 | [API耗时] 208ms
21:08:08.431 | [响应成功]: from:tag-props
21:08:08.431 | [API耗时] 3001ms
21:08:08.453 | info  - Generating static pages (40/40)
21:08:08.455 |  
21:08:08.456 | > Build error occurred
21:08:08.458 | Error: Export encountered errors on following paths:
21:08:08.458 | /archive
21:08:08.458 | at /vercel/path0/node_modules/next/dist/export/index.js:409:19
21:08:08.458 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
21:08:08.458 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:08:08.459 | at async /vercel/path0/node_modules/next/dist/build/index.js:1345:21
21:08:08.459 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:08:08.459 | at async /vercel/path0/node_modules/next/dist/build/index.js:1205:17
21:08:08.459 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:08:08.459 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:66:29)
21:08:08.538 | error Command failed with exit code 1.
21:08:08.538 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:08:08.563 | Error: Command "yarn run build" exited with 1
```

部署的 log 

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/10231735/210366108-147d2d0b-b2d6-4acf-8109-e143d676397a.png">

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/10231735/210364797-a5138003-66df-4836-9c18-42bad14cd695.png">

**相应配置**
notion_page_id: `2237a8e9a84d4e8ab46923e6f3ccfd5d`

网站一直没有生成成功

**Comment by tangly1024** [comment]
hi，针对您的问题，我提交了一个修复补丁，请尝试更新到最新版的代码即可。
