### ISSUE TITLE
【部署问题】Medium 主题部署报错

### ISSUE THREAD

**Issue by SkysCrystal** [tangly1024/NotionNext#915]
**描述bug**
3-25 更新 Github 库后，开启 `NEXT_PUBLIC_CUSTOM_MENU`。
在 Notion 里设置好 `Type`  `Menu` ，同样的配置 `simple` 主题可以显示[*](https://www.dsuper.xyz/)， `medium` 主题报如下错误：

```
TypeError: Cannot read property 'map' of undefined
--
10:37:56.802 | at MenuBarMobile (/vercel/path0/.next/server/chunks/323.js:15999:25)
10:37:56.802 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
10:37:56.803 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
10:37:56.803 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
10:37:56.803 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
10:37:56.803 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
10:37:56.803 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
10:37:56.803 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
10:37:56.803 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
10:37:56.803 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
10:37:56.820 |  
10:37:56.820 | Error occurred prerendering page "/category/[category]". Read more: https://nextjs.org/docs/messages/prerender-error
10:37:56.820 | TypeError: Cannot read property 'map' of undefined
10:37:56.820 | at MenuBarMobile (/vercel/path0/.next/server/chunks/323.js:15999:25)
10:37:56.820 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
10:37:56.820 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
10:37:56.820 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
10:37:56.821 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
10:37:56.821 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
10:37:56.821 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
10:37:56.821 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
10:37:56.821 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
10:37:56.821 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

```

**复现步骤**
切换 medium 主题重新部署即会报错

**期望的正常结果**
正常显示内容

**截图**
暂无

**环境**

- 操作系统: windows
- 浏览器 chrome
- 版本 [e.g. 22]

**补充说明**
暂无

**Comment by tangly1024** [comment]
提交了一个补丁，更新体验

**Comment by SkysCrystal** [comment]
完美解决！谢谢~~
